/*
 * $Id: package-info.java,v 1.2 2011/09/13 13:43:28 pah Exp $
 * Copyright 2011 Paul Harrison (paul.harrison@manchester.ac.uk)
 *
 * File originally generated by JAXB, but since hand updated
 */
/**
 * Classes used in the Registry Interface. The {@link net.ivoa.resource.registry.iface.VOResources} class can be used to aggregate a number of {@link net.ivoa.resource.Resource} elements.
 */
@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.ivoa.net/xml/RegistryInterface/v1.0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package net.ivoa.resource.registry.iface;
