/*
 * $Id: ResourceNameSingle.java,v 1.2 2011/09/13 13:43:29 pah Exp $
 * Copyright 2011 Paul Harrison (paul.harrison@manchester.ac.uk)
 *
 * File originally generated by JAXB, but since hand updated
 */


package net.ivoa.resource;

import javax.persistence.Embeddable;



/**
 * 
 *          the name of a potentially registered resource.  That is, the entity
 *          referred to may have an associated identifier.
 *        
 * 
 * <p>Java class for ResourceName complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ResourceName">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>token">
 *       &lt;attribute name="ivo-id" type="{http://www.ivoa.net/xml/VOResource/v1.0}IdentifierURI" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */

@Embeddable
public class ResourceNameSingle extends AbstractResourceName implements ResourceName {
     
}
