<?xml version="1.0"?>
<definitions    name="JobControllerService"
                targetNameSpace="http//www.astrogrid.org/wsdl/JobController.wsdl"
                xmlns="http//schemas.xmlsoap.org/wsdl/"
                xmlns:soap="http//schemas.xmlsoap.org/wsdl/soap"
                xmlns:tns="http//www.astrogrid.org/wsdl/JobController.wsdl"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema">

        <message name="submitJobRequest">
                <part name="submitXML" type="xsd:string"/>
        </message>
        <message name="submitJobResponse">
                <part name="submitXML" type="xsd:string"/>
        </message>

        <portType name="JobControllerPortType">
                <operation name="submitJob">
                        <input message="tns:submitJobRequest" />
                        <output message="tns:submitJobResponse" />
                </operation>
        </portType>

        <binding name="JobControllerBinding" type="tns:JobControllerPortType">
                <soap:binding style ="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        </binding>

        <service name="JobControllerService"> 
                <port binding="tns:JobControllerBinding" name="JobControllerPortType">
                <documentation>The JobControllerService is the interface whereby jobs
                are submitted for processing within AstroGrid. Internally AstroGrid will store,
                schedule and monitor their execution.  
                </documentation>
                <soap:address location="http://hydra.star.le.ac.uk:8080/axis/services/JobController">
        </service>
</definitions>
