/* Generated By: AdqlStoX.jjt,v 1.18 2007/07/25 12&JJTree: Do not edit this line. AST_ConvexHullLatLon.java */

package org.astrogrid.adql;

import org.apache.xmlbeans.XmlObject;
import org.astrogrid.stc.beans.*;
import org.apache.commons.logging.Log ;
import org.apache.commons.logging.LogFactory ;

public class AST_ConvexHullLatLon extends SimpleNode {
    
  private static Log log = LogFactory.getLog( AST_ConvexHullLatLon.class ) ;

  public AST_ConvexHullLatLon(AdqlStoX p, int id) {
    super(p, id) ;
  }
  
  public void buildXmlTree( XmlObject xo ) {
      if( log.isTraceEnabled() ) enterTrace( log, "AST_ConvexHullLatLon.buildXmlTree()" ) ; 
      getTracker().setType( ConvexHullType.type ) ;
      //
      // We know this is a LatLon Convex Hull type, else why are we here.
      // So set the appropriate astro coord system...
      AST_RegionPredicate.setAstroCoordSystem_J2000( this ) ;
      //
      // "Create" the appropriate polygon type using XmlBeans magic.
      ConvexHullType p = (ConvexHullType)xo.changeType( ConvexHullType.type ) ;
    
      this.generatedObject = p ;
      super.buildXmlTree(p) ;
      if( log.isTraceEnabled() ) exitTrace( log, "AST_ConvexHullLatLon.buildXmlTree()" ) ; 
  }

}
