/* Generated By: AdqlStoX.jjt,v 1.18 2007/07/25 12&JJTree: Do not edit this line. AST_ConvexHullCartesian.java */

package org.astrogrid.adql;

import org.apache.xmlbeans.XmlObject;
import org.astrogrid.stc.beans.*;
import org.apache.commons.logging.Log ;
import org.apache.commons.logging.LogFactory ;

public class AST_ConvexHullCartesian extends SimpleNode {
    
  private static Log log = LogFactory.getLog( AST_ConvexHullCartesian.class ) ;

  public AST_ConvexHullCartesian(AdqlStoX p, int id) {
    super(p, id) ;
    setPositionType( ConvexHullType.type ) ;
  }
  
  public void buildXmlTree( XmlObject xo ) {
      if( log.isTraceEnabled() ) enterTrace( log, "AST_ConvexHullCartesian.buildXmlTree()" ) ; 
      setPositionType( ConvexHullType.type ) ;
      //
      // We know this is a Cartesian Convex Hull type, else why are we here.
      // So set the appropriate astro coord system...
      AST_RegionPredicate.setAstroCoordSystem_Cartesian( this ) ;
      //
      // "Create" the appropriate polygon type using XmlBeans magic.
      ConvexHullType p = (ConvexHullType)xo.changeType( ConvexHullType.type ) ;
    
      this.generatedObject = p ;
      super.buildXmlTree(p) ;
      if( log.isTraceEnabled() ) exitTrace( log, "AST_ConvexHullCartesian.buildXmlTree()" ) ; 
  }

}

