/* Generated By: AdqlStoX.jjt,v 1.10 2007/07/13 15&JJTree: Do not edit this line. AST_CircleJ2000.java */

package org.astrogrid.adql;

import org.apache.xmlbeans.XmlObject;
import org.astrogrid.adql.beans.AtomType;
import org.astrogrid.adql.beans.IntegerType;
import org.astrogrid.adql.beans.LiteralType;
import org.astrogrid.adql.beans.RealType;
import org.astrogrid.adql.beans.StringType;
import org.astrogrid.adql.beans.RegionSearchType;
import org.astrogrid.adql.beans.LinkedListType;
import org.astrogrid.adql.beans.ScalarExpressionType;
import org.astrogrid.adql.beans.UnaryExprType;

import org.astrogrid.stc.beans.*;
import org.apache.commons.logging.Log ;
import org.apache.commons.logging.LogFactory ;

public class AST_CircleJ2000 extends SimpleNode {
    
  private static Log log = LogFactory.getLog( AST_CircleJ2000.class ) ;


  public AST_CircleJ2000(AdqlStoX p, int id) {
    super(p, id) ;
  }
  
  public void buildXmlTree( XmlObject xo ) {
      if( log.isTraceEnabled() ) enterTrace( log, "AST_CircleJ2000.buildXmlTree()" ) ; 
      
      ( (AST_RegionPredicate)this.parent ).setAstroCoordSystem_J2000() ;
   
      CircleType circle = (CircleType)xo.changeType( CircleType.type ) ;
      Double2Type center = circle.addNewCenter() ;

      LinkedListType llt = this.getCurrentLinkedElementList() ;
      int currentLinkedArrayPosition = llt.sizeOfLinkedElementArray() ;
      
      ScalarExpressionType setRa = llt.addNewLinkedElement() ;
      children[0].buildXmlTree( setRa ) ;
      setRa = (ScalarExpressionType)children[0].getGeneratedObject() ;
          
      Double1Type d1tRa = center.addNewC1() ;
      Double d = this.unpackNumericLiteral( setRa ) ;
      if( d != null ) {
          d1tRa.setDoubleValue( d.doubleValue() ) ;
          llt.removeLinkedElement( currentLinkedArrayPosition ) ;
      }
      else {
          String uid = this.formUniqueID() ;
          setRa.setId( uid ) ;
          d1tRa.setIdref( uid ) ;
          currentLinkedArrayPosition++ ;
      }
      
      ScalarExpressionType setDec = llt.addNewLinkedElement() ;
      children[1].buildXmlTree( setDec ) ;
      setDec = (ScalarExpressionType)children[1].getGeneratedObject() ;
      
      Double1Type d1tDec = center.addNewC2() ;
      d = this.unpackNumericLiteral( setDec ) ;
      if( d != null ) {
          d1tDec.setDoubleValue( d.doubleValue() ) ;
          llt.removeLinkedElement( currentLinkedArrayPosition ) ;
      }
      else {
          String uid = this.formUniqueID() ;
          setDec.setId( uid ) ;
          d1tDec.setIdref( uid ) ;
          currentLinkedArrayPosition++ ;
      }
          
      Double1Type d1tRad = circle.addNewRadius() ;
      ScalarExpressionType setRadius = llt.addNewLinkedElement() ;
      children[2].buildXmlTree( setRadius ) ;
      setRadius = (ScalarExpressionType)children[2].getGeneratedObject() ;     
      d = this.unpackNumericLiteral( setRadius ) ;
      if( d != null ) {
          d1tRad.setDoubleValue( d.doubleValue() ) ;
          llt.removeLinkedElement( currentLinkedArrayPosition ) ;
      } else {
          String uid = this.formUniqueID() ;
          setRadius.setId( uid ) ;
          d1tRad.setIdref( uid ) ;
      }
      this.generatedObject = circle ;
      super.buildXmlTree(circle) ;
      if( log.isTraceEnabled() ) exitTrace( log, "AST_CircleJ2000.buildXmlTree()" ) ; 
  }

}
