/* Generated By: AdqlStoX.jjt,v 1.10 2007/07/13 15&JJTree: Do not edit this line. AST_RegionPredicate.java */

package org.astrogrid.adql;

import org.apache.xmlbeans.XmlObject;
import org.astrogrid.adql.beans.RegionSearchType;
import org.astrogrid.stc.beans.*;
import org.apache.commons.logging.Log ;
import org.apache.commons.logging.LogFactory ;

public class AST_RegionPredicate extends SimpleNode {

    private static Log log = LogFactory.getLog( AST_RegionPredicate.class ) ;
    
  public AST_RegionPredicate(AdqlStoX p, int id) {
    super(p, id);
  }
  
  public void buildXmlTree( XmlObject xo ) {
      if( log.isTraceEnabled() ) enterTrace( log, "AST_RegionPredicate.buildXmlTree()" ) ; 
      RegionSearchType rst = (RegionSearchType)xo.changeType( RegionSearchType.type ) ;
     
//      center.setC1() ;
//      
//      circle.addNewCenter() ;
//      circle.addNewRadius() ;
//      
//      int childCount = jjtGetNumChildren() ;
//      String[] nameArray = new String[ childCount ] ;
//      for( int i=0; i<childCount; i++ ) {
//          nameArray[i] = (String)children[i].getGeneratedObject() ;
//      }
//      cnlType.setColumnNameArray( nameArray ) ;
      this.generatedObject = rst ;
      super.buildXmlTree(rst) ;
      if( log.isTraceEnabled() ) exitTrace( log, "AST_RegionPredicate.buildXmlTree()" ) ; 
  }

}
