/* Generated By: AdqlStoX.jjt,v 1.33.2.4 2006-12-19 14&JJTree: Do not edit this line. AST_ValueExpressionPrimary.java */

package org.astrogrid.adql;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.apache.xmlbeans.XmlObject;
import org.astrogrid.adql.beans.ClosedExprType ;

public class AST_ValueExpressionPrimary extends SimpleNode {
    /**
     * Logger for this class
     */
    private static final Log log = LogFactory.getLog(AST_ValueExpressionPrimary.class);
    
    private boolean parenthesized = false ;

    public AST_ValueExpressionPrimary(AdqlStoX p, int id) {
        super(p, id);
    }

    public void setParenthesized( String elementName ) {
        this.parenthesized = true ;
        pushPosition( elementName, ClosedExprType.type ) ;
    }

 
    public void buildXmlTree( XmlObject xo ) {
        if( log.isTraceEnabled() ) { enterTrace( log, "AST_ValueExpressionPrimary.buildXmlTree()" ) ; }

        if( parenthesized ) {
            ClosedExprType ceType = (ClosedExprType)xo.changeType( ClosedExprType.type ) ;
            children[0].buildXmlTree( ceType.addNewArg() ) ;
            setGeneratedObject( ceType ) ;  
        }
        else {
            children[0].buildXmlTree( xo ) ;
            setGeneratedObject( children[0].getGeneratedObject() ) ;  
        }
        super.buildXmlTree( (XmlObject)this.generatedObject ) ;
        if( log.isTraceEnabled() ) { exitTrace( log, "AST_ValueExpressionPrimary.buildXmlTree()" ) ; }
 
    }
  
}
