/* Generated By: AdqlStoX.jjt,v 1.13 2007/07/17 16&JJTree: Do not edit this line. AST_CircleCartesian.java */

package org.astrogrid.adql;

public class AST_CircleCartesian extends SimpleNode {
  public AST_CircleCartesian(int id) {
    super(id);
  }

  public AST_CircleCartesian(AdqlStoX p, int id) {
    super(p, id);
  }

}
