/* Generated By: AdqlStoX.jjt,v 1.33.2.4 2006-12-19 14&JJTree: Do not edit this line. AST_Table.java */

package org.astrogrid.adql;

import java.util.ArrayList;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory; 
import org.apache.xmlbeans.XmlObject; 
import org.astrogrid.adql.beans.DerivedTableType;
import org.astrogrid.adql.beans.JoinTableType;
import org.astrogrid.adql.beans.TableType;

public class AST_Table extends SimpleNode {
    
    private static Log log = LogFactory.getLog( AST_Table.class ) ;

    public AST_Table(AdqlStoX p, int id) {
        super(p, id);
    }

    public void buildXmlTree( XmlObject ftt ) { 
        if( log.isTraceEnabled() ) enterTrace( log, "AST_Table.buildXmlTree()" ) ;

        int childCount = jjtGetNumChildren() ;
        if( childCount == 0 ) {
          //
          // This is just a safety first measure.
          // It should fail somewhere else, but without a NullPointerException
            setGeneratedObject( TableType.Factory.newInstance() ) ;
        }
        else if( children[0] instanceof AST_TableName ) {
            TableType tt = (TableType)ftt.changeType( TableType.type ) ;           
            ArrayList dotQualifications = (ArrayList) children[0].getGeneratedObject() ;
            String[] names = new String[ dotQualifications.size() ] ;
            names = (String[])dotQualifications.toArray( names ) ;
            for( int i=0; i<names.length; i++ ) {
                if( i==0 ) {
                    tt.setName( names[names.length - (i+1) ] ) ;
                }
                else if( i==1 ) {
                    tt.setSchema( names[names.length - (i+1) ] ) ;
                }
                else if( i==2 ) {
                    tt.setCatalog( names[names.length - (i+1) ] ) ;
                }
            }
            if( childCount > 1 ) {
                tt.setAlias( (String)children[1].getGeneratedObject() ) ;
            }
            setGeneratedObject( tt ) ;    
        }
        else if( children[0] instanceof AST_TableSubQuery ) {
            children[0].buildXmlTree( ftt ) ;
            DerivedTableType dtt = (DerivedTableType)ftt ;
            dtt.setAlias( (String)children[1].getGeneratedObject() ) ;
            setGeneratedObject( dtt ) ;           
        }
        else if( children[0] instanceof AST_QualifiedJoin ) {
            children[0].buildXmlTree( ftt ) ;
            setGeneratedObject( children[0].getGeneratedObject() ) ;
        }
        else {
            log.warn( "Unrecognized table type." ) ;
        }
        super.buildXmlTree( (XmlObject)this.generatedObject ) ;
        if( log.isTraceEnabled() ) exitTrace( log, "AST_Table.buildXmlTree()" ) ; 
    }
    
}

