/* Generated By: AdqlStoX.jjt,v 1.33.2.4 2006-12-19 14&JJTree: Do not edit this line. AST_JoinType.java */

package org.astrogrid.adql;

import org.astrogrid.adql.beans.JoinTableQualifierType;

public class AST_JoinType extends SimpleNode {
 
    public AST_JoinType(AdqlStoX p, int id) {
        super(p, id);
    }

    public void jjtClose() {
        JoinTableQualifierType jType = JoinTableQualifierType.Factory.newInstance() ;

        switch ( firstToken.kind ) {
        case AdqlStoXConstants.INNER :
            jType.set( JoinTableQualifierType.INNER );
            break;
        case AdqlStoXConstants.LEFT :
            jType.set( JoinTableQualifierType.LEFT_OUTER );
            break;
        case AdqlStoXConstants.RIGHT :
            jType.set( JoinTableQualifierType.RIGHT_OUTER );
            break;
        case AdqlStoXConstants.FULL :
            jType.set( JoinTableQualifierType.FULL_OUTER );
            break;
        }  
        setGeneratedObject( jType ) ;
    }

}
