/* Generated By: AdqlStoX.jjt,v 1.33.2.4 2006-12-19 14&JJTree: Do not edit this line. AST_SortSpecificationList.java */

package org.astrogrid.adql;

import org.astrogrid.adql.beans.OrderExpressionType ;
import org.apache.xmlbeans.XmlObject; 
import org.apache.commons.logging.Log ;
import org.apache.commons.logging.LogFactory ;

public class AST_SortSpecificationList extends SimpleNode {
    
    private static Log log = LogFactory.getLog( AST_SortSpecificationList.class ) ;
 
    public AST_SortSpecificationList(AdqlStoX p, int id) {
        super(p, id);
        this.schemaType = OrderExpressionType.type ;
    }

    public void buildXmlTree( XmlObject xo ) {
        if( log.isTraceEnabled() ) enterTrace( log, "AST_SortSpecificationList.buildXmlTree()" ) ;
        OrderExpressionType oeType = (OrderExpressionType)xo.changeType( OrderExpressionType.type ) ;
        int childCount = jjtGetNumChildren() ;
        for( int i=0; i<childCount; i++ ) {
            children[i].buildXmlTree( oeType.addNewItem() ) ;
        }
        setGeneratedObject( oeType ) ;
        super.buildXmlTree( oeType ) ;
        if( log.isTraceEnabled() ) exitTrace( log, "AST_SortSpecificationList.buildXmlTree()" ) ;
    }

}
