DROP DATABASE @OPENJMS.JDBC.DATABASE@;
DROP USER @OPENJMS.JDBC.USER@;

CREATE USER @OPENJMS.JDBC.USER@ CREATEDB PASSWORD '@OPENJMS.JDBC.PASSWORD@';
CREATE DATABASE @OPENJMS.JDBC.DATABASE@ WITH OWNER @OPENJMS.JDBC.USER@;

COMMIT;
