/* Generated By: AdqlStoX.jjt,v 1.33.2.4 2006-12-19 14&JJTree: Do not edit this line. AST_NumericValueFunction.java */

package org.astrogrid.adql; 

//
// Class should be removed.

public class AST_NumericValueFunction extends SimpleNode {
 
    public AST_NumericValueFunction(AdqlStoX p, int id) {
        super(p, id);
    }

}
