/* Generated By: AdqlStoX.jjt,v 1.34.2.26 2007/05/08 15&JJTree: Do not edit this line. AST_CharacterStringLiteral.java */

package org.astrogrid.adql;

import org.astrogrid.adql.beans.AtomType ;
import org.apache.xmlbeans.XmlObject ;
import org.apache.commons.logging.Log ;
import org.apache.commons.logging.LogFactory ;

public class AST_CharacterStringLiteral extends SimpleNode {

    private static Log log = LogFactory.getLog( AST_CharacterStringLiteral.class ) ;

    public AST_CharacterStringLiteral(AdqlStoX p, int id) {
        super(p, id);
    }

    public void buildXmlTree(XmlObject xo) {
        if( log.isTraceEnabled() ) enterTrace( log, "AST_CharacterStringLiteral.buildXmlTree()" ) ;
        AtomType at = (AtomType)xo.changeType( AtomType.type ) ;
        children[0].buildXmlTree( at.addNewLiteral() ) ;
        if( log.isDebugEnabled() ) {
            log.debug( "at.getLiteral(): " + at.getLiteral() ) ;
        }
        this.setGeneratedObject( at ) ;
        super.buildXmlTree(at) ;
        if( log.isTraceEnabled() ) exitTrace( log, "AST_CharacterStringLiteral.buildXmlTree()" ) ;
    }

}
