/* Generated By: AdqlStoX.jjt,v 1.33.2.4 2006-12-19 14&JJTree: Do not edit this line. AST_ColumnReference.java */

package org.astrogrid.adql;

import org.apache.commons.logging.Log ;
import org.apache.commons.logging.LogFactory ;
import org.astrogrid.adql.beans.*;
import org.apache.xmlbeans.XmlObject ;
import org.astrogrid.adql.AdqlParser.SyntaxOption; 

public class AST_ColumnReference extends SimpleNode {
    
    private static Log log = LogFactory.getLog( AST_ColumnReference.class ) ;
    
    public AST_ColumnReference(AdqlStoX p, int id) {
        super(p, id);
        this.schemaType = ColumnReferenceType.type ;
    }

    public void buildXmlTree( XmlObject xo ) {   
        if( log.isTraceEnabled() ) enterTrace( log, "AST_ColumnReference.buildXmlTree()" ) ; 
        ColumnReferenceType crt = (ColumnReferenceType)xo.changeType( ColumnReferenceType.type ) ;
        adqlstox.parser.addColumnReference( crt ) ;

        int childCount = jjtGetNumChildren() ;
        if( childCount == 1 ) {
            crt.setName( (String)children[0].getGeneratedObject() ) ;
        }
        else {

            if( childCount == 2 ) {               
                crt.setName( (String)children[1].getGeneratedObject() ) ;
                crt.setTable( (String)children[0].getGeneratedObject() ) ;
            }
            else { 
                //
                // Child count must be three and we have table
                // qualified by some idea of ownership...
                crt.setName( (String)children[2].getGeneratedObject() ) ;
                crt.setTable( (String)children[1].getGeneratedObject() ) ;
                AST_Ownership ownership = (AST_Ownership)children[0] ; ;
                if( ownership.getQualifierDepth() == 1 ) {
                    crt.setSchema( ownership.getSecondQualifier() ) ;
                }
                else {
                    crt.setCatalog( ownership.getFirstQualifier() ) ;
                    crt.setSchema( ownership.getSecondQualifier() ) ;
                    if( crt.getSchema() == "" ) {
                        if( !adqlstox.parser.isSyntaxSet( SyntaxOption.LAX_SCHEMA ) ) {
                            this.getTracker().setError( "Reference Implementation: Schema names must be fully qualified." ) ;
                        }
                    }
                }
            } 
        }  
        setGeneratedObject( crt ) ;
        super.buildXmlTree (crt ) ;
        if( log.isTraceEnabled() ) exitTrace( log, "AST_ColumnReference.buildXmlTree()" ) ; 
    }

}
