/* Generated By: AdqlStoX.jjt,v 1.33.2.4 2006-12-19 14&JJTree: Do not edit this line. AST_OrderByClause.java */

package org.astrogrid.adql;

import org.apache.xmlbeans.XmlObject;
import org.apache.commons.logging.Log ;
import org.apache.commons.logging.LogFactory ;
import org.astrogrid.adql.beans.OrderExpressionType;
import org.astrogrid.adql.beans.OrderType;

public class AST_OrderByClause extends SimpleNode {
    
    private static Log log = LogFactory.getLog( AST_OrderByClause.class ) ;

    public AST_OrderByClause(AdqlStoX p, int id) {
        super(p, id);
    }

    public void buildXmlTree(XmlObject xo) {
        if( log.isTraceEnabled() ) enterTrace( log, "AST_OrderByClause.buildXmlTree()" ) ; 
        children[0].buildXmlTree(xo) ;
        setGeneratedObject( children[0].getGeneratedObject() ) ;
        if( log.isTraceEnabled() ) exitTrace( log, "AST_OrderByClause.buildXmlTree()" ) ; 
    }
    
}
