/* Generated By: AdqlStoX.jjt,v 1.33.2.4 2006-12-19 14&JJTree: Do not edit this line. AST_LikePredicate.java */

package org.astrogrid.adql;

import org.astrogrid.adql.beans.BetweenPredType;
import org.astrogrid.adql.beans.LikePredType ;
import org.astrogrid.adql.beans.NotLikePredType ;
import org.apache.xmlbeans.XmlObject ;
import org.apache.commons.logging.Log ;
import org.apache.commons.logging.LogFactory ;

public class AST_LikePredicate extends SimpleNode {
    
    private static Log log = LogFactory.getLog( AST_LikePredicate.class ) ;
    
    private boolean like = true ;

    public AST_LikePredicate(AdqlStoX p, int id) {
        super(p, id);
        this.schemaType = LikePredType.type ;
    }

    public void setLike( boolean like ) {
        this.like = like ;
        this.setPositionType( NotLikePredType.type ) ;
    }

    public void buildXmlTree( XmlObject xo ) {
        if( log.isTraceEnabled() ) enterTrace( log, "AST_LikePredicate.buildXmlTree()" ) ; 
        if( like ) {
            LikePredType lpt = (LikePredType)xo.changeType( LikePredType.type ) ;
            children[0].buildXmlTree( lpt.addNewArg() ) ;
            children[1].buildXmlTree( lpt.addNewPattern() ) ;
            setGeneratedObject( lpt ) ;
        }
        else {
            NotLikePredType nlpt = (NotLikePredType)xo.changeType( NotLikePredType.type ) ;
            children[0].buildXmlTree( nlpt.addNewArg() ) ;
            children[1].buildXmlTree( nlpt.addNewPattern() ) ;
            setGeneratedObject( nlpt ) ;
        }
        super.buildXmlTree( (XmlObject)this.generatedObject ) ;
        if( log.isTraceEnabled() ) exitTrace( log, "AST_LikePredicate.buildXmlTree()" ) ; 
    } 
}

