/* Generated By: AdqlStoX.jjt,v 1.33.2.4 2006-12-19 14&JJTree: Do not edit this line. AST_GroupBy.java */

package org.astrogrid.adql;

import org.apache.commons.logging.Log ;
import org.apache.commons.logging.LogFactory ;
import org.apache.xmlbeans.XmlObject ;
import org.astrogrid.adql.beans.GroupByType;

public class AST_GroupBy extends SimpleNode {
    
    private static Log log = LogFactory.getLog( AST_GroupBy.class ) ;
    
    public AST_GroupBy(AdqlStoX p, int id) {
        super(p, id);
        this.elementName = AdqlParser.GROUPBY_ELEMENT ;
        this.schemaType = GroupByType.type ;
    }
     
    //
    // Basically a pass through...
    public void buildXmlTree( XmlObject xo ) { 
        if( log.isTraceEnabled() ) enterTrace( log, "AST_GroupBy.buildXmlTree()" ) ;
        children[0].buildXmlTree( xo ) ;
        this.generatedObject = children[0].getGeneratedObject() ;
        if( log.isTraceEnabled() ) exitTrace( log, "AST_GroupBy.buildXmlTree()" ) ;
    }

}
