/* Generated By: AdqlStoX.jjt,v 1.4 2007/07/12 13&JJTree: Do not edit this line. AST_ExistsPredicate.java */

package org.astrogrid.adql;

import org.apache.xmlbeans.XmlObject;
import org.astrogrid.adql.beans.ExistsPredType;
import org.apache.commons.logging.Log ;
import org.apache.commons.logging.LogFactory ;

public class AST_ExistsPredicate extends SimpleNode {
    
    private static Log log = LogFactory.getLog( AST_ExistsPredicate.class ) ;

  public AST_ExistsPredicate(AdqlStoX p, int id) {
    super(p, id);
    this.schemaType = ExistsPredType.type ;
  }
  
  public void buildXmlTree( XmlObject xo ) {
      if( log.isTraceEnabled() ) enterTrace( log, "AST_ExistsPredicate.buildXmlTree()" ) ; 
      ExistsPredType epType = (ExistsPredType)xo.changeType( ExistsPredType.type ) ;
      children[0].buildXmlTree( epType.addNewSubQuery() ) ;
      this.generatedObject = epType ;
      super.buildXmlTree(xo) ;
      if( log.isTraceEnabled() ) exitTrace( log, "AST_ExistsPredicate.buildXmlTree()" ) ; 
  }

}
