/* Generated By: AdqlStoX.jjt,v 1.33.2.4 2006-12-19 14&JJTree: Do not edit this line. AST_Pattern.java */

package org.astrogrid.adql;

public class AST_Pattern extends SimpleNode {

    public AST_Pattern(AdqlStoX p, int id) {
        super(p, id);
    }

}
