/* Generated by Together */

package mySpaceRegistry;

import java.util.Vector;

public class Container {
    /** To add DataItems
     *
     * */
    public boolean add() {
    	return true;
    }

    /** To remove DataItems
     *
     * */
    public boolean delete() {
        return true;
    }

    public String getContainerID(){ return containerID; }

    public void setContainerID(String containerID){ this.containerID = containerID; }

    /**
     * @link aggregation 
     */
    private DataItem lnkParent;

    /**
     * @link aggregation 
     */
    private Container lnkContainer;
    private String containerID;
}
