/* Generated by Together */

package org.astrogrid.mySpace.mySpaceRegistry;

import org.astrogrid.mySpace.mySpaceServer.DataHolder;
import java.util.Calendar;
import java.util.Date;

public class DataItemRecord {
    protected String getDataItemID() {
        return dataItemID;
    }

    protected void setDataItemID(String dataItemID) {
        this.dataItemID = dataItemID;
    }

    protected String getDataItemName() {
        return dataItemName;
    }

    protected void setDataItemName(String dataItemName) {
        this.dataItemName = dataItemName;
    }

    public String getState(){ return state; }

    public void setState(String state){ this.state = state; }

    protected String getSecurityMask() {
        return securityMask;
    }

    protected void setSecurityMask(String securityMask) {
        this.securityMask = securityMask;
    }

    /** checkes if the Data is nearly expired
     * */
    public boolean nearlyExpired() {
        //if Calendar.getDate - this.creationTime >= length of time(some time before the expired time length)
        //return true;(eg. -- in MySpaceExplore this piece of data turns red.)
        return true;
    }

    private String dataItemID;
    private String state;
    private String securityMask;
    private String dataItemName;
    private Date creationDate = Calendar.getInstance().getTime();
    private Date expireDate; // creationDate + magic number of (days..)
    private long timeRemaining = expireDate.getTime() - creationDate.getTime();
    private String absoluteFileName;
    private String ownerID;

    /**
     * @clientCardinality 1
     * @supplierCardinality 1 
     */
    private DataHolder lnkDataHolder;
    private int dataHolderID;
}
