/* Generated by Together */

package org.astrogrid.mySpace.mySpaceRegistry;

import org.astrogrid.mySpace.mySpaceServer.Manager;
import org.astrogrid.mySpace.mySpaceServer.MSSvrIF;
import java.util.Vector;

/**
 * @testcase test.org.astrogrid.mySpace.mySpaceRegistry.TestManager 
 */
public class Manager {
    public String processRequest(){ }

    private boolean validateUser() {
    }

    private String community;

    /**
     * @directed
     * @label calls 
     */
    private MSSvrIF lnkMSSvrIF;

    /**
     * @link aggregation 
     */
    private UserAccount lnkUserAccount;
    private Vector users;
}
