/* Generated by Together */

package org.astrogrid.mySpace.mySpaceRegistry;

/**
 * @stereotype boundary 
 */
public interface MSRegIF {
    String processRequest();

    /** @link dependency */
    /*# Manager lnkManager; */
}
