/* Generated by Together */

package org.astrogrid.mySpace.mySpaceRegistry;

/**
 * @testcase test.org.astrogrid.mySpace.mySpaceRegistry.TestUserAccount 
 */
public class UserAccount {
    protected String getUserID() {
        return userID;
    }

    protected void setUserID(String userID) {
        this.userID = userID;
    }

    protected String getCommunity() {
        return community;
    }

    protected void setCommunity(String community) {
        this.community = community;
    }

    private String userID;
    private String community;

    /**
     * @link aggregation 
     */
    private Container lnkContainer;
}
