//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.03.11 at 03:50:58 PM GMT 
//


package net.ivoa.resource.vospace;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import net.ivoa.resource.Capability;


/**
 * 
 *             Indicates that a service has vospace capability
 *          
 * 
 * <p>Java class for VOSpaceCapability complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VOSpaceCapability">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ivoa.net/xml/VOResource/v1.0}Capability">
 *       &lt;sequence>
 *         &lt;element name="accessPolicy" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="protocols" type="{http://www.ivoa.net/schema/VOSpaceResource/v1.0rc7}AcceptorProvider"/>
 *         &lt;element name="views" type="{http://www.ivoa.net/schema/VOSpaceResource/v1.0rc7}AcceptorProvider"/>
 *         &lt;element name="nodeTypes" type="{http://www.ivoa.net/schema/VOSpaceResource/v1.0rc7}NodeTypes" maxOccurs="unbounded"/>
 *         &lt;element name="capacity" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="quota" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="retentionPolicy" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="features" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VOSpaceCapability", propOrder = {
    "accessPolicy",
    "protocols",
    "views",
    "nodeTypes",
    "capacity",
    "quota",
    "retentionPolicy",
    "features"
})
public class VOSpaceCapability
    extends Capability
{

    @XmlElement(required = true)
    protected String accessPolicy;
    @XmlElement(required = true)
    protected AcceptorProvider protocols;
    @XmlElement(required = true)
    protected AcceptorProvider views;
    @XmlElement(required = true, type = NodeTypes.class)
    protected List<NodeTypes> nodeTypes;
    protected String capacity;
    protected Boolean quota;
    protected String retentionPolicy;
    @XmlElement(type = String.class)
    protected List<String> features;

    /**
     * Gets the value of the accessPolicy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccessPolicy() {
        return accessPolicy;
    }

    /**
     * Sets the value of the accessPolicy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccessPolicy(String value) {
        this.accessPolicy = value;
    }

    /**
     * Gets the value of the protocols property.
     * 
     * @return
     *     possible object is
     *     {@link AcceptorProvider }
     *     
     */
    public AcceptorProvider getProtocols() {
        return protocols;
    }

    /**
     * Sets the value of the protocols property.
     * 
     * @param value
     *     allowed object is
     *     {@link AcceptorProvider }
     *     
     */
    public void setProtocols(AcceptorProvider value) {
        this.protocols = value;
    }

    /**
     * Gets the value of the views property.
     * 
     * @return
     *     possible object is
     *     {@link AcceptorProvider }
     *     
     */
    public AcceptorProvider getViews() {
        return views;
    }

    /**
     * Sets the value of the views property.
     * 
     * @param value
     *     allowed object is
     *     {@link AcceptorProvider }
     *     
     */
    public void setViews(AcceptorProvider value) {
        this.views = value;
    }

    /**
     * Gets the value of the nodeTypes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nodeTypes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNodeTypes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NodeTypes }
     * 
     * 
     */
    public List<NodeTypes> getNodeTypes() {
        if (nodeTypes == null) {
            nodeTypes = new ArrayList<NodeTypes>();
        }
        return this.nodeTypes;
    }

    /**
     * Gets the value of the capacity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCapacity() {
        return capacity;
    }

    /**
     * Sets the value of the capacity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCapacity(String value) {
        this.capacity = value;
    }

    /**
     * Gets the value of the quota property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isQuota() {
        return quota;
    }

    /**
     * Sets the value of the quota property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setQuota(Boolean value) {
        this.quota = value;
    }

    /**
     * Gets the value of the retentionPolicy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRetentionPolicy() {
        return retentionPolicy;
    }

    /**
     * Sets the value of the retentionPolicy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRetentionPolicy(String value) {
        this.retentionPolicy = value;
    }

    /**
     * Gets the value of the features property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the features property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFeatures().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getFeatures() {
        if (features == null) {
            features = new ArrayList<String>();
        }
        return this.features;
    }

}
