DROP DATABASE @XMLBLASTER.JDBC.DATABASE@;
DROP USER @XMLBLASTER.JDBC.USER@;

CREATE USER @XMLBLASTER.JDBC.USER@ CREATEDB PASSWORD '@XMLBLASTER.JDBC.PASSWORD@';
CREATE DATABASE @XMLBLASTER.JDBC.DATABASE@ WITH OWNER @XMLBLASTER.JDBC.USER@;

COMMIT;
