//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.03.11 at 03:35:57 PM GMT 
//


package org.astrogrid.applications.description.cea;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import net.ivoa.resource.Capability;
import org.astrogrid.applications.description.base.ApplicationBase;


/**
 * 
 * 	         The definition of a capability conforming to the CEA
 * 	         specification, capable of running one or more
 * 	         CeaApplications
 * 	      
 * 
 * <p>Java class for CeaCapability complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CeaCapability">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ivoa.net/xml/VOResource/v1.0}Capability">
 *       &lt;choice>
 *         &lt;element name="managedApplications" type="{http://www.ivoa.net/xml/CEA/v1.0rc1}ManagedApplications"/>
 *         &lt;element name="applicationDefinition" type="{http://www.ivoa.net/xml/CEA/base/v1.0rc3}ApplicationBase"/>
 *       &lt;/choice>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CeaCapability", propOrder = {
    "managedApplications",
    "applicationDefinition"
})
public class CeaCapability
    extends Capability
{
    public CeaCapability() {
	this.setStandardID("ivo://org.astrogrid/std/CEA/v1.0");
	this.managedApplications = new ManagedApplications();
    }

    protected ManagedApplications managedApplications;
    protected ApplicationBase applicationDefinition;

    /**
     * Gets the value of the managedApplications property.
     * 
     * @return
     *     possible object is
     *     {@link ManagedApplications }
     *     
     */
    public ManagedApplications getManagedApplications() {
        return managedApplications;
    }

    /**
     * Sets the value of the managedApplications property.
     * 
     * @param value
     *     allowed object is
     *     {@link ManagedApplications }
     *     
     */
    public void setManagedApplications(ManagedApplications value) {
        this.managedApplications = value;
    }

    /**
     * Gets the value of the applicationDefinition property.
     * 
     * @return
     *     possible object is
     *     {@link ApplicationBase }
     *     
     */
    public ApplicationBase getApplicationDefinition() {
        return applicationDefinition;
    }

    /**
     * Sets the value of the applicationDefinition property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApplicationBase }
     *     
     */
    public void setApplicationDefinition(ApplicationBase value) {
        this.applicationDefinition = value;
    }

}
