/*
 * $Id: ServiceStandard.java,v 1.2 2011/09/13 13:43:27 pah Exp $
 * Copyright 2011 Paul Harrison (paul.harrison@manchester.ac.uk)
 *
 * File originally generated by JAXB, but since hand updated
 */


package net.ivoa.resource.standard;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Entity;
import javax.persistence.OneToMany;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import net.ivoa.resource.Interface;


/**
 * 
 *            This typically refers to an IVOA standard but is not
 *            limited to such.  
 *          
 * 
 * <p>Java class for ServiceStandard complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ServiceStandard">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ivoa.net/xml/StandardsRegExt/v1.0}Standard">
 *       &lt;sequence>
 *         &lt;element name="interface" type="{http://www.ivoa.net/xml/VOResource/v1.0}Interface" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@Entity
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ServiceStandard", propOrder = {
    "_interface"
})
public class ServiceStandard
    extends Standard
{

    @OneToMany
    @XmlElement(name = "interface", type = Interface.class)
    protected List<Interface> _interface;

    /**
     * Gets the value of the interface property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the interface property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInterface().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Interface }
     * 
     * 
     */
    public List<Interface> getInterface() {
        if (_interface == null) {
            _interface = new ArrayList<Interface>();
        }
        return this._interface;
    }

}
