/*$Id: VizierDelegate.java,v 1.2 2004/10/18 13:11:30 mch Exp $
 * Created on 16-Oct-2003
 *
 * Copyright (C) AstroGrid. All rights reserved.
 *
 * This software is published under the terms of the AstroGrid
 * Software License version 1.2, a copy of which has been included
 * with this distribution in the LICENSE.txt file.
 *
**/
package org.astrogrid.datacenter.impl.cds.vizier;

import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.rmi.RemoteException;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.rpc.ServiceException;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.astrogrid.datacenter.impl.cds.generated.vizier.VizieR;
import org.astrogrid.datacenter.impl.cds.generated.vizier.VizieRService;
import org.astrogrid.datacenter.impl.cds.generated.vizier.VizieRServiceLocator;
import org.astrogrid.util.DomHelper;
import org.w3c.dom.Document;
import org.xml.sax.SAXException;

/** Delegate around the soap client generated by wsdl2java
 * @todo - refine the parameters to web methods - can lift from strings to enumerated constants (once we
 * find out what these constants are).
 * @author Noel Winstanley nw@jb.man.ac.uk 16-Oct-2003
 *
 */
public class VizierDelegate {
    static Log log = LogFactory.getLog(VizierDelegate.class);
    
    /** construct delegate connected to default service endpoint */
    public VizierDelegate() throws ServiceException {
        VizieRService service = new VizieRServiceLocator();
        vizier = service.getVizieR();
    }
    /** construct a delegate connected to the specified endpoint */
    public VizierDelegate(String endpoint) throws MalformedURLException, ServiceException {
        this(new URL(endpoint));
    }
    /** construct a delegate connected to the specified endpoint */
    public VizierDelegate(URL endpoint) throws ServiceException {
        VizieRService service = new VizieRServiceLocator();
        vizier  = service.getVizieR(endpoint);
    }
    
    protected VizieR vizier;
    
    /**Access all metadata
     */
    public String getAllMetadata() throws IOException {
        return vizier.metaAll();
    }

    public String cataloguesData(Target target,double radius,Unit unit) throws RemoteException, ParserConfigurationException, SAXException, IOException {
        return cataloguesData(target,radius,unit,"");
    }

    public String cataloguesData(Target target, double radius, Unit unit, String text) throws RemoteException, ParserConfigurationException, SAXException, IOException {
        if (log.isDebugEnabled()) {
            log.debug("cataloguesData " + target.toString() + " " + radius + " " + unit.toString() + " " + text);
        }
        return vizier.cataloguesData(target.toString(),radius,unit.toString(),text);
    }
    
    public String cataloguesData(Target target,double radius,Unit unit,Wavelength wavelength) throws RemoteException, ParserConfigurationException, SAXException, IOException {
        return cataloguesData(target,radius,unit,wavelength,"");
    }
    
    public String cataloguesData(Target target, double radius, Unit unit, Wavelength wavelength, String text) throws RemoteException, ParserConfigurationException, SAXException, IOException {
        if (log.isDebugEnabled()) {
            log.debug("cataloguesData " + target.toString() + " " + radius + " " + unit.toString() + " " + wavelength.toString() + " " + text);
        }
        return vizier.cataloguesData(target.toString(),radius,unit.toString(),text,wavelength.toString());
    }

}


/*
$Log: VizierDelegate.java,v $
Revision 1.2  2004/10/18 13:11:30  mch
Lumpy Merge

Revision 1.1.4.1  2004/10/15 19:59:05  mch
Lots of changes during trip to CDS to improve int test pass rate

Revision 1.1  2004/10/05 19:19:18  mch
Merged CDS implementation into PAL

Revision 1.3  2004/09/29 18:45:55  mch
Bringing Vizier into line with new(er) metadata stuff

Revision 1.2  2003/12/01 16:50:30  nw
first working tested version

Revision 1.1  2003/11/18 11:23:49  nw
mavenized cds delegate

Revision 1.2  2003/11/18 11:10:05  nw
mavenized cds delegate

Revision 1.1  2003/10/16 10:11:45  nw
first check in
 
*/
