/*
 * $Id: package-info.java,v 1.2 2011/09/13 13:43:32 pah Exp $
 * Copyright 2011 Paul Harrison (paul.harrison@manchester.ac.uk)
 *
 * File originally generated by JAXB, but since hand updated
 */
/**
 * Classes representing the Cone Search Schema.
 */
@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.ivoa.net/xml/ConeSearch/v1.0")
package net.ivoa.resource.cone;
