/*$Id: VoSpaceTest.java,v 1.1 2004/04/15 14:55:38 mch Exp $
 * Created on 05-Sep-2003
 *
 * Copyright (C) AstroGrid. All rights reserved.
 *
 * This software is published under the terms of the AstroGrid
 * Software License version 1.2, a copy of which has been included
 * with this distribution in the LICENSE.txt file.
 *
**/
package org.astrogrid.store.integration;

import java.io.IOException;
import java.net.URISyntaxException;
import junit.framework.Test;
import junit.framework.TestCase;
import junit.framework.TestSuite;
import org.astrogrid.community.User;
import org.astrogrid.store.Ivorn;
import org.astrogrid.store.VoSpaceClient;
import org.astrogrid.store.delegate.StoreFile;

/** Tests the vospace client, which needs to talk to registry etc
 *
 * @author mch
 */

public class VoSpaceTest extends TestCase {

   private static User testUser;
   private static Ivorn MYSPACEIVO;
   private static VoSpaceClient client;
   private static String root;
   
   public void setUp() throws IOException, URISyntaxException {
      
      MYSPACEIVO = new Ivorn("ivo://org.astrogrid.localhost/myspace");
      
      root = "avodemo/";
      
      testUser = new User("avodemo", "test.astrogrid.org", "token");
   
      client = new VoSpaceClient(testUser);
      
   }
   
   public void testStoreAccess() throws IOException
   {
   }

   private Ivorn createTestFile(String filename) throws IOException, URISyntaxException {
      Ivorn fileIvorn = new Ivorn(MYSPACEIVO.toString()+"#"+root+filename);
      
      String contents="This file is generated by the VoSpaceTest";
      client.putBytes(contents.getBytes(), 0, contents.length()-1, fileIvorn, false);

      return fileIvorn;
   }
   
   /** Tests getFile etc - if these are failing the rest of the tests might
    * not make much sense.  This is a bit of a combined one anyway... */
   public void testGetFile() throws IOException, URISyntaxException
   {
      Ivorn fileRn = createTestFile("newfile.txt");
      
      //check it's created OK
      StoreFile file = client.getFile(fileRn);
      
      assertNotNull(file);
      
      assertTrue(file.isFile());
      
      //tidy up
      client.delete(fileRn);
   }

  
   public void testMove() throws IOException, URISyntaxException
   {
      Ivorn source = createTestFile("moveSource.txt");
      Ivorn target = new Ivorn(MYSPACEIVO.toString()+"#"+root+"moveTarget.txt");
      
      client.move(source, target);
      
      StoreFile file = client.getFile(target);
      assertNotNull(file);
      assertTrue(file.isFile());
      
      //@todo check that the new file is the same as the created file... sometime
      
      //tidy up
      client.delete(source);
      client.delete(target);
   }

   public void testCopy() throws IOException, URISyntaxException
   {
      Ivorn source = createTestFile("copySource.txt");
      Ivorn target = new Ivorn(MYSPACEIVO.toString()+"#"+root+"copyTarget.txt");
      
      client.move(source, target);
      
      StoreFile file = client.getFile(target);
      assertNotNull(file);
      assertTrue(file.isFile());
      
      //@todo check that the new file is the same as the created file... sometime

      //tidy up
      client.delete(source);
      client.delete(target);
   }
   
   public void testDelete() throws IOException, URISyntaxException
   {
      Ivorn fileRn = createTestFile("deleteFile.txt");
      
      //check it's created OK
      StoreFile file = client.getFile(fileRn);
      
      assertNotNull(file);
      
      assertTrue(file.isFile());
      
      //delete
      client.delete(fileRn);
      
      file = client.getFile(fileRn);
      
      assertNull(file);
   }
   
    /**
     * Assembles and returns a test suite made up of all the testXxxx() methods
      * of this class.
     */
    public static Test suite() {
        // Reflection is used here to add all the testXXX() methods to the suite.
        return new TestSuite(VoSpaceTest.class);
    }

    /**
     * Runs the test case.
     */
    public static void main(String args[])
    {
       junit.textui.TestRunner.run(suite());
    }

}


/*
$Log: VoSpaceTest.java,v $
Revision 1.1  2004/04/15 14:55:38  mch
New IVORN resolver tester


*/

