/*$Id: VoSpaceTest.java,v 1.4 2004/04/21 12:31:56 KevinBenson Exp $
 * Created on 05-Sep-2003
 *
 * Copyright (C) AstroGrid. All rights reserved.
 *
 * This software is published under the terms of the AstroGrid
 * Software License version 1.2, a copy of which has been included
 * with this distribution in the LICENSE.txt file.
 *
**/
package org.astrogrid.store.integration;

import java.io.IOException;
import java.net.URISyntaxException;
import junit.framework.Test;
import junit.framework.TestCase;
import junit.framework.TestSuite;
import org.astrogrid.community.User;
import org.astrogrid.store.Agsl;
import org.astrogrid.store.Ivorn;
import org.astrogrid.store.VoSpaceClient;
import org.astrogrid.store.delegate.StoreFile;
import org.astrogrid.store.delegate.VoSpaceResolver;

/** Tests the vospace client, which needs to talk to registry etc
 *
 * @author mch
 */

public class VoSpaceTest extends TestCase {

   private static User testUser;
   private static Ivorn MYSPACEIVO;
   private static Ivorn HOMESPACETARGETIVO;
   private static Ivorn TESTUSERIVO;
   private static VoSpaceClient client;
   private static String root;
   
   public void setUp() throws IOException, URISyntaxException {
      
      MYSPACEIVO = new Ivorn("ivo://org.astrogrid.localhost/myspace");
      HOMESPACETARGETIVO = new Ivorn("ivo://org.astrogrid.localhost/myspace");
      TESTUSERIVO = new Ivorn("ivo://org.astrogrid.localhost/localtest");
      
      root = "localtest/";
      
      testUser = new User("testuser", "org.astrogrid.localhost", "token");
   
      client = new VoSpaceClient(testUser);
      
   }
   
   public void testCreateUser() throws IOException, URISyntaxException {
      System.out.println("entered testCreateUser()");
      Ivorn iv = client.createUser(HOMESPACETARGETIVO,TESTUSERIVO);
      System.out.println("the result of createUser = " + iv.toString());
      System.out.println("exit testCreateUser()");      
   }
   
   public void testResolver() throws IOException
   {
      System.out.println("entering testResolver");
      Agsl myspaceAgsl = VoSpaceResolver.resolveAgsl(MYSPACEIVO);
      System.out.println("agsl myspaceAgsl = " + myspaceAgsl.toString());
      assertNotNull(myspaceAgsl);
      System.out.println("exiting testResolver");
   }

/*
   public void testStoreAccess() throws IOException
   {
   }
*/
   private Ivorn createTestFile(String filename) throws IOException, URISyntaxException {
      System.out.println("entering createTestFile");
      Ivorn fileIvorn = new Ivorn(MYSPACEIVO.toString()+"#"+root+filename);
      
      String contents="This file is generated by the VoSpaceTest";
      System.out.println("the fileIvorn return = " + fileIvorn.toString());
      client.putBytes(contents.getBytes(), 0, contents.length()-1, fileIvorn, false);
      System.out.println("exiting createTestFile");
      return fileIvorn;
   }
   
   /** Tests getFile etc - if these are failing the rest of the tests might
    * not make much sense.  This is a bit of a combined one anyway... */
   public void testGetFile() throws IOException, URISyntaxException
   {
      System.out.println("entering testGetFile and creating newfile.txt");
      Ivorn fileRn = createTestFile("newfile.txt");
      
      //check it's created OK
      StoreFile file = client.getFile(fileRn);
      
      assertNotNull(file);
      
      assertTrue(file.isFile());
      
      //tidy up
      System.out.println("now deleting the newfile.txt");
      client.delete(fileRn);
      System.out.println("exiting testGetFile");
   }

  
   public void testMove() throws IOException, URISyntaxException
   {
      System.out.println("enter testMove moving- moveSource.txt to moveTarget.txt");
      Ivorn source = createTestFile("moveSource.txt");
      Ivorn target = new Ivorn(MYSPACEIVO.toString()+"#"+root+"moveTarget.txt");
      
      System.out.println("now moving");
      client.move(source, target);
      
      StoreFile file = client.getFile(target);
      assertNotNull(file);
      assertTrue(file.isFile());
      
      //@todo check that the new file is the same as the created file... sometime
      
      //tidy up
      System.out.println("now deleting the moveSource and moveTarget");
      client.delete(source);
      client.delete(target);
      System.out.println("exiting testMove");      
   }

   public void testCopy() throws IOException, URISyntaxException
   {
      System.out.println("enter testCopy() copySource.txt to copyTarget.txt");
      Ivorn source = createTestFile("copySource.txt");
      Ivorn target = new Ivorn(MYSPACEIVO.toString()+"#"+root+"copyTarget.txt");
      
      System.out.println("copying");
      client.copy(source, target);
      
      
      StoreFile file = client.getFile(target);
      assertNotNull(file);
      assertTrue(file.isFile());
      
      //@todo check that the new file is the same as the created file... sometime

      //tidy up
      System.out.println("now deleting copySource and copyTarget");
      client.delete(source);
      client.delete(target);
      System.out.println("exiting testCopy()");
   }
   
   public void testDelete() throws IOException, URISyntaxException
   {
      System.out.println("entering testDelete() first createTestFile(deleteFile.txt)");
      Ivorn fileRn = createTestFile("deleteFile.txt");
      
      //check it's created OK
      StoreFile file = client.getFile(fileRn);
      
      assertNotNull(file);
      
      assertTrue(file.isFile());
      
      //delete
      client.delete(fileRn);
      
      file = client.getFile(fileRn);
      
      assertNull(file);
      System.out.println("exiting testDelete()");
   }
   
   public void testDeleteUser() throws IOException, URISyntaxException {
      System.out.println("entered testDeleteUser()");
      client.deleteUser(HOMESPACETARGETIVO,TESTUSERIVO);
      //Ivorn iv = client.(HOMESPACETARGETIVO,TESTUSERIVO);
      //System.out.println("the result of createUser = " + iv.toString());
      System.out.println("exit testCreateUser()");      
   }
   
   
    /**
     * Assembles and returns a test suite made up of all the testXxxx() methods
      * of this class.
     */
    public static Test suite() {
        // Reflection is used here to add all the testXXX() methods to the suite.
        return new TestSuite(VoSpaceTest.class);
    }

    /**
     * Runs the test case.
     */
    public static void main(String args[])
    {
       junit.textui.TestRunner.run(suite());
    }

}


/*
$Log: VoSpaceTest.java,v $
Revision 1.4  2004/04/21 12:31:56  KevinBenson
*** empty log message ***

Revision 1.3  2004/04/16 15:58:45  KevinBenson
create and delete user working through vospaceclient

Revision 1.2  2004/04/15 15:12:35  mch
Added resolver test

Revision 1.1  2004/04/15 14:55:38  mch
New IVORN resolver tester


*/


