/*$Id: VoSpaceTest.java,v 1.8 2004/05/11 11:23:00 pah Exp $
 * Created on 05-Sep-2003
 *
 * Copyright (C) AstroGrid. All rights reserved.
 *
 * This software is published under the terms of the AstroGrid
 * Software License version 1.2, a copy of which has been included
 * with this distribution in the LICENSE.txt file.
 *
**/
package org.astrogrid.store.integration;

import java.io.BufferedInputStream;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.net.URISyntaxException;
import junit.framework.Test;
import junit.framework.TestCase;
import junit.framework.TestSuite;
import org.astrogrid.community.User;
import org.astrogrid.integration.AbstractTestForIntegration;
import org.astrogrid.store.Agsl;
import org.astrogrid.store.Ivorn;
import org.astrogrid.store.VoSpaceClient;
import org.astrogrid.store.delegate.StoreException;
import org.astrogrid.store.delegate.StoreFile;
import org.astrogrid.store.delegate.VoSpaceResolver;

/** Tests the vospace client, which needs to talk to registry etc
 *
 * @author mch
 */

public class VoSpaceTest extends AbstractTestForIntegration {

   /**
    * @param arg0
    */
   public VoSpaceTest(String arg0) {
      super(arg0);
      // TODO Auto-generated constructor stub
   }

   private String TESTCONTENTS ="this is the contents of the test file";
   private static User testUser;
   private static Ivorn MYSPACEIVO;
   private static Ivorn HOMESPACETARGETIVO;
   private static Ivorn TESTUSERIVO;
   private static VoSpaceClient client;
   private static String root;
   
   public void setUp() throws Exception {
      super.setUp();
      
      MYSPACEIVO = new Ivorn("ivo://org.astrogrid.localhost/myspace");
      HOMESPACETARGETIVO = new Ivorn("ivo://org.astrogrid.localhost/myspace");
      TESTUSERIVO = new Ivorn("ivo://org.astrogrid.localhost/localtest");
      
      root = "localtest/";
      
      testUser = new User("testuser", "org.astrogrid.localhost", "group", "token");
   
      client = new VoSpaceClient(testUser);
      
   }
   
   public void testCreateUser() throws IOException, URISyntaxException {
      
      //delete user first in case previous test failed
      try {
         client.deleteUser(HOMESPACETARGETIVO, TESTUSERIVO);
      }
      catch (StoreException se) {
         //ignore
      }
      
      Ivorn iv = client.createUser(HOMESPACETARGETIVO,TESTUSERIVO);
   }
   
   public void testResolver() throws IOException
   {
      System.out.println("entering testResolver");
      Agsl myspaceAgsl = VoSpaceResolver.resolveAgsl(MYSPACEIVO);
      System.out.println("agsl myspaceAgsl = " + myspaceAgsl.toString());
      assertNotNull(myspaceAgsl);
      System.out.println("exiting testResolver");
   }


   public void testStoreAccess() throws IOException, URISyntaxException
   {
      System.out.println("enter testStoreAccess");
      Ivorn resultIvorn = createTestFile("hello.txt");
      System.out.println("the resultIvorn = " + resultIvorn.toString());
      System.out.println("exit testStoreAccess");
      
   }

   private Ivorn createTestFile(String filename) throws IOException, URISyntaxException {
      System.out.println("entering createTestFile");
      Ivorn fileIvorn = new Ivorn(MYSPACEIVO.toString()+"#"+root+filename);
      
      String contents="This file is generated by the VoSpaceTest";
      System.out.println("the fileIvorn return = " + fileIvorn.toString());
      client.putBytes(contents.getBytes(), 0, contents.length()-1, fileIvorn, false);
      System.out.println("exiting createTestFile");
      return fileIvorn;
   }
   
   /** Tests getFile etc - if these are failing the rest of the tests might
    * not make much sense.  This is a bit of a combined one anyway... */
   
   public void testGetFile() throws IOException, URISyntaxException
   {
      Ivorn fileRn = createTestFile("newfile.txt");
      
      //check it's created OK
      StoreFile file = client.getFile(fileRn);
      
      assertNotNull(file);
      
      assertTrue(file.isFile());
      
      //tidy up
      client.delete(fileRn);
   }
  
   public void testMove() throws IOException, URISyntaxException
   {
      Ivorn source = createTestFile("moveSource.txt");
      Ivorn target = new Ivorn(MYSPACEIVO.toString()+"#"+root+"moveTarget.txt");

      //delete target in case it's already there
      try {
         client.delete(target);
      }
      catch (StoreException se) {
         //ignore
      }
      
      client.move(source, target);

      //check the source is gone
      StoreFile file = client.getFile(source);
      assertNull(file);
      
      //check the target exists
      file = client.getFile(target);
      assertNotNull(file);
      assertTrue(file.isFile());
      
      //@todo check that the new file is the same as the created file... sometime
      
      //tidy up
      client.delete(target);
   }

   public void testCopy() throws IOException, URISyntaxException
   {
      Ivorn source = createTestFile("copySource.txt");
      Ivorn target = new Ivorn(MYSPACEIVO.toString()+"#"+root+"copyTarget.txt");
      
      //delete target in case it's already there
      try {
         client.delete(target);
      }
      catch (StoreException se) {
         //ignore
      }

      client.copy(source, target);
      
      
      StoreFile file = client.getFile(target);
      assertNotNull(file);
      assertTrue(file.isFile());
      
      //@todo check that the new file is the same as the created file... sometime

      //tidy up
      client.delete(source);
      client.delete(target);
   }
   
   public void testDelete() throws IOException, URISyntaxException
   {
      System.out.println("entering testDelete() first createTestFile(deleteFile.txt)");
      Ivorn fileRn = createTestFile("deleteFile.txt");
      
      //check it's created OK
      StoreFile file = client.getFile(fileRn);
      
      assertNotNull(file);
      
      assertTrue(file.isFile());
      
      //delete
      client.delete(fileRn);
      
      file = client.getFile(fileRn);
      
      assertNull(file);
      System.out.println("exiting testDelete()");
   }
   
   public void testDeleteUser() throws IOException, URISyntaxException {
      System.out.println("entered testDeleteUser()");
      //client.deleteUser(HOMESPACETARGETIVO,TESTUSERIVO);
      //Ivorn iv = client.(HOMESPACETARGETIVO,TESTUSERIVO);
      //System.out.println("the result of createUser = " + iv.toString());
      System.out.println("exit testCreateUser()");
   }

   
   /**
    * tests simply storing a file in vospace for the frog user who should pre-exist
    */
   public void testFrogStoreFile() throws IOException
   {
    VoSpaceClient voclient = new VoSpaceClient(user);
    assertNotNull(voclient);
      
    Ivorn inputIvorn = createIVORN("/vospaceFile");   
    assertNotNull(inputIvorn);
    byte[] bytes = TESTCONTENTS.getBytes();
    voclient.putBytes(bytes, 0, bytes.length, inputIvorn, false); 
    InputStream st = voclient.getStream(inputIvorn);
    assertNotNull(st);
    
    BufferedReader br = new BufferedReader(new InputStreamReader(st));
    String instr;
    StringBuffer sb = new StringBuffer();
    while ((instr = br.readLine()) != null) {
      sb.append(instr);
   }
   assertTrue("the contents of the saved file are not the same", TESTCONTENTS.contentEquals(sb));
    
    //TODO add some more tests...  
    
        

      
   }
   
    /**
     * Assembles and returns a test suite made up of all the testXxxx() methods
      * of this class.
     */
    public static Test suite() {
        // Reflection is used here to add all the testXXX() methods to the suite.
        return new TestSuite(VoSpaceTest.class);
    }

    /**
     * Runs the test case.
     */
    public static void main(String args[])
    {
       junit.textui.TestRunner.run(suite());
    }
    
    

}


/*
$Log: VoSpaceTest.java,v $
Revision 1.8  2004/05/11 11:23:00  pah
*** empty log message ***

Revision 1.7  2004/05/11 08:07:40  pah
corrected the creation of the user object

Revision 1.6  2004/04/21 16:53:53  mch
Fixes to tests

Revision 1.5  2004/04/21 16:50:35  KevinBenson
just addeda  few more comments.  And setup the user corectly.

Revision 1.4  2004/04/21 12:31:56  KevinBenson
*** empty log message ***

Revision 1.3  2004/04/16 15:58:45  KevinBenson
create and delete user working through vospaceclient

Revision 1.2  2004/04/15 15:12:35  mch
Added resolver test

Revision 1.1  2004/04/15 14:55:38  mch
New IVORN resolver tester


*/



