/*
 $Id: AceDictionary.java,v 1.1.1.1 2003/08/25 18:36:14 mch Exp $

 Date       Author      Changes
 $date$     M Hill      Created

 (c) Copyright...
 */

package org.astrogrid.ace.service;

import org.astrogrid.common.wrapper.LocalTermDictionary;

/**
 * AceDictionary is the local term dictionary for the ACE (SExtractor)
 * application.
 * Note that this is a LOCAL dictionary for LOCAL terms - the UCDs are given
 * for information and convertion but are not necessary.  Terms are listed
 * as required or not according to the local native files - they may not
 * even exist to the external user - for example CATALOG_NAME is necessary
 * to SExtractor but is generated by the wrapper, not the external user
 *
 * @version %I%
 * @author M Hill
 */

public class AceDictionary extends LocalTermDictionary
{

   private static AceDictionary INSTANCE = new AceDictionary();

   public static final String OUTPUT_COLUMNS_LABEL = "OUTPUT_COLUMNS";

   /** Constructs the dictionary from hardwired terms for the moment. At some
    * point this should come from (or have a method to allow it to come from)
    * a configuration file - or even better the schema.
    */
   private AceDictionary()
   {
      super();

      addTerm(null, "ImageToCatalog", null, true);
      addTerm(null, "ImageToMeasure", null, true);

      addTerm(null, "Wavelength", null, false);
      addTerm(null, "Passband", null, false);

      addTerm(null, "CATALOG_NAME", null, true);
      addTerm(null, "CATALOG_TYPE", null, true);

      addTerm(null, "PARAMETERS_NAME", null, true);
      //extraction
      addTerm(null, "DETECT_TYPE", null, true);
      addTerm(null, "FLAG_IMAGE", null, false);
      addTerm(null, "DETECT_MINAREA", null, true);
      addTerm(null, "DETECT_THRESH", null, true);
      addTerm(null, "ANALYSIS_THRESH", null, true);
      addTerm(null, "FILTER", null, true);
      addTerm(null, "FILTER_NAME", null, true);
      addTerm(null, "DEBLEND_NTHRESH", null, true);
      addTerm(null, "DEBLEND_MINCONT", null, true);
      addTerm(null, "CLEAN", null, true);
      addTerm(null, "CLEAN_PARAM", null, true);
      addTerm(null, "MASK_TYPE", null, true);

      //photometry
      addTerm(null, "PHOT_APERTURES", null, true);
      addTerm(null, "PHOT_AUTOPARAMS", null, true);
      addTerm(null, "SATUR_LEVEL", null, true);
      addTerm(null, "MAG_ZEROPOINT", null, true);
      addTerm(null, "MAG_GAMMA", null, true);
      addTerm(null, "GAIN", null, true);
      addTerm(null, "PIXEL_SCALE", null, true);

      //star/galaxy separation
      addTerm(null, "SEEING_FWHM", null, true);
      addTerm(null, "STARNNW_NAME", null, true);

      //background
      addTerm(null, "BACK_SIZE", null, true);
      addTerm(null, "BACK_FILTERSIZE", null, true);
      addTerm(null, "BACKPHOTO_TYPE", null, true);
      addTerm(null, "BACKPHOTO_THICK", null, false);

      //check image
      addTerm(null, "CHECKIMAGE_TYPE", null, false);
      addTerm(null, "CHECKIMAGE_NAME", null, false);

      //memory
      addTerm(null, "MEMORY_OBJSTACK", null, true);
      addTerm(null, "MEMORY_PIXSTACK", null, true);
      addTerm(null, "MEMORY_BUFSIZE", null, true);


      //misc
      addTerm(null, "VERBOSE_TYPE", null, true);

      //image location
//      addTerm(null, "ImageToMeasure", null, true);
//      addTerm(null, "ImageToCatalog", null, true);

      //output columns list
      addTerm(null, OUTPUT_COLUMNS_LABEL, null, true);


      //output columns
      addTerm("POS_EQ_RA_MAIN", "X_WORLD", null, false);
      addTerm("POS_EQ_DEC_MAIN", "Y_WORLD", null, false);

      addTerm("PHOT_MAG", "MAG_AUTO", null, false);


   }

   /**
    * Returns an array of strings listing all the terms suitable for the
    * native 'config' file.
    */
   public String[] getLocalConfigFileDictionary()
   {
      return new String[] {
         "CATALOG_NAME", "CATALOG_TYPE",
            "PARAMETERS_NAME",
            "DETECT_TYPE", "FLAG_IMAGE", "DETECT_MINAREA", "DETECT_THRESH",
            "ANALYSIS_THRESH", "FILTER", "FILTER_NAME",
            "DEBLEND_NTHRESH", "DEBLEND_MINCONT",
            "CLEAN", "CLEAN_PARAM",
            "MASK_TYPE",
            "PHOT_APERTURES","PHOT_AUTOPARAMS",
            "SATUR_LEVEL",
            "MAG_ZEROPOINT", "MAG_GAMMA", "GAIN", "PIXEL_SCALE",
            "SEEING_FWHM","STARNNW_NAME",
            "BACK_SIZE","BACK_FILTERSIZE","BACKPHOTO_TYPE","BACKPHOTO_THICK",
            "CHECKIMAGE_TYPE","CHECKIMAGE_NAME",
            "MEMORY_OBJSTACK","MEMORY_PIXSTACK","MEMORY_BUFSIZE",
            "VERBOSE_TYPE"
      };
   }

   public static synchronized AceDictionary getInstance()
   {
      return INSTANCE;
   }

}

