/* Generated by Together */

public class ContentHandler {
    /**
     * @link aggregation 
     */
    /*# ResponseFormatter lnkContentHandler; */

    /**
     * @link aggregation 
     */
    /*# RequestGenerator lnkContentHandler1; */
}

