/*$Id: BeanFacade.java,v 1.4 2004/03/04 01:57:35 nw Exp $
 * Created on 11-Feb-2004
 *
 * Copyright (C) AstroGrid. All rights reserved.
 *
 * This software is published under the terms of the AstroGrid 
 * Software License version 1.2, a copy of which has been included 
 * with this distribution in the LICENSE.txt file.  
 *
**/
package org.astrogrid.jes.job;
import org.astrogrid.community.beans.v1.Account;
import org.astrogrid.jes.JesException;
import org.astrogrid.jes.types.v1.JobURN;
import org.astrogrid.jes.types.v1.SubmissionResponse;
import org.astrogrid.jes.types.v1.WorkflowList;
import org.astrogrid.workflow.beans.v1.Workflow;

import java.util.Iterator;
/** Interface that separates details of object model implementation from the service implementations
 * @author Noel Winstanley nw@jb.man.ac.uk 11-Feb-2004
 *
 */
public interface  BeanFacade {

    /** return a reference to the factory object provided by the current implementation */
    public abstract JobFactory getJobFactory() throws JesException;
    /** factory method to create a request object for the job controller */
    public abstract SubmitJobRequest createSubmitJobRequest(String xmlDoc) throws JesException;
    /** facotry method to create a response object */
    public abstract WorkflowList createListJobsErrorResponse(Account acc,       String message);
    public abstract WorkflowList createListJobsSuccessResponse(Account acc, Iterator iterator);
    public abstract SubmissionResponse createSubmitJobSuccessResponse(Workflow j);
    public abstract SubmissionResponse createSubmitJobErrorResponse(Workflow j, String msg);

}
/* 
$Log: BeanFacade.java,v $
Revision 1.4  2004/03/04 01:57:35  nw
major refactor.
upgraded to latest workflow object model.
removed internal facade
replaced community snippet with objects

Revision 1.3  2004/03/03 01:13:42  nw
updated jes to work with regenerated workflow object model

Revision 1.2  2004/02/27 00:46:03  nw
merged branch nww-itn05-bz#91

Revision 1.1.2.9  2004/02/19 13:34:23  nw
cut out useless classes,
moved constants into generated code.

Revision 1.1.2.8  2004/02/17 12:25:38  nw
improved javadocs for classes

Revision 1.1.2.7  2004/02/17 10:57:54  nw
cut down facade interface, matched with types
generated by wsdl2java

Revision 1.1.2.6  2004/02/12 12:54:47  nw
worked in inversion of control pattern - basically means that
components have to be assembled, rather than self-configuring
from properties in config files. so easier to test each component in isolation

Revision 1.1.2.5  2004/02/12 01:15:09  nw
made bean factory configurable
 
*/