/* Generated By: AdqlStoX.jjt,v 1.38.4.1 2008/04/15 14&JJTree: Do not edit this line. ./AdqlStoXTreeConstants.java */

package org.astrogrid.adql;

public interface AdqlStoXTreeConstants
{
  public int JJTACTUALIDENTIFIER = 0;
  public int JJTVOID = 1;
  public int JJTBETWEENPREDICATE = 2;
  public int JJTBOOLEANPRIMARY = 3;
  public int JJTBOOLEANTERM = 4;
  public int JJTBOOLEANFACTOR = 5;
  public int JJTLIKEPREDICATE = 6;
  public int JJTCHARACTERSTRINGLITERAL = 7;
  public int JJTASCIISTRINGLITERAL = 8;
  public int JJTASCIISTRINGLITERALPART = 9;
  public int JJTCOLUMNNAME = 10;
  public int JJTCOLUMNREFERENCE = 11;
  public int JJTVALUEEXPRESSIONPRIMARY = 12;
  public int JJTCOMPARISON = 13;
  public int JJTCOMPARISONPREDICATE = 14;
  public int JJTCORRELATIONNAME = 15;
  public int JJTEXACTNUMERICLITERAL = 16;
  public int JJTFACTOR = 17;
  public int JJTSIGN = 18;
  public int JJTFROM = 19;
  public int JJTGENERALSETFUNCTION = 20;
  public int JJTGROUPBY = 21;
  public int JJTGROUPINGCOLUMNREFERENCELIST = 22;
  public int JJTHAVING = 23;
  public int JJTINPREDICATE = 24;
  public int JJTINPREDICATEVALUE = 25;
  public int JJTINVALUELIST = 26;
  public int JJTINVALUELISTCONSTANT = 27;
  public int JJTJOINTYPE = 28;
  public int JJTMATCHVALUE = 29;
  public int JJTMATHFUNCTION = 30;
  public int JJTNUMERICVALUEEXPRESSION = 31;
  public int JJTUSERDEFINEDFUNCTION = 32;
  public int JJTORDERBYCLAUSE = 33;
  public int JJTSORTSPECIFICATIONLIST = 34;
  public int JJTSORTSPECIFICATION = 35;
  public int JJTORDERINGSPECIFICATION = 36;
  public int JJTQUALIFIEDJOIN = 37;
  public int JJTTABLEARRAYFRAGMENT = 38;
  public int JJTQUALIFIEDNAME = 39;
  public int JJTSCHEMANAME = 40;
  public int JJTSELECT = 41;
  public int JJTSEARCHCONDITION = 42;
  public int JJTSELECTIONLIST = 43;
  public int JJTALLSELECTIONITEM = 44;
  public int JJTSELECTSUBLIST = 45;
  public int JJTDERIVEDCOLUMN = 46;
  public int JJTSETFUNCTIONSPECIFICATION = 47;
  public int JJTSETFUNCTIONSPECIFICATIONPARTFRAGMENT = 48;
  public int JJTRESTRICT = 49;
  public int JJTALLOW = 50;
  public int JJTTABLENAME = 51;
  public int JJTTABLE = 52;
  public int JJTTABLEREFERENCEBARJOINEDTABLE = 53;
  public int JJTTABLESUBQUERY = 54;
  public int JJTTERM = 55;
  public int JJTTRIGFUNCTION = 56;
  public int JJTAPPROXIMATENUMERICLITERAL = 57;
  public int JJTVALUEEXPRESSION = 58;
  public int JJTWHERE = 59;


  public String[] jjtNodeName = {
    "ActualIdentifier",
    "void",
    "BetweenPredicate",
    "BooleanPrimary",
    "BooleanTerm",
    "BooleanFactor",
    "LikePredicate",
    "CharacterStringLiteral",
    "ASCIIStringLiteral",
    "ASCIIStringLiteralPart",
    "ColumnName",
    "ColumnReference",
    "ValueExpressionPrimary",
    "Comparison",
    "ComparisonPredicate",
    "CorrelationName",
    "ExactNumericLiteral",
    "Factor",
    "Sign",
    "From",
    "GeneralSetFunction",
    "GroupBy",
    "GroupingColumnReferenceList",
    "Having",
    "InPredicate",
    "InPredicateValue",
    "InValueList",
    "InValueListConstant",
    "JoinType",
    "MatchValue",
    "MathFunction",
    "NumericValueExpression",
    "UserDefinedFunction",
    "OrderByClause",
    "SortSpecificationList",
    "SortSpecification",
    "OrderingSpecification",
    "QualifiedJoin",
    "TableArrayFragment",
    "QualifiedName",
    "SchemaName",
    "Select",
    "SearchCondition",
    "SelectionList",
    "AllSelectionItem",
    "SelectSublist",
    "DerivedColumn",
    "SetFunctionSpecification",
    "SetFunctionSpecificationPartFragment",
    "Restrict",
    "Allow",
    "TableName",
    "Table",
    "TableReferenceBarJoinedTable",
    "TableSubQuery",
    "Term",
    "TrigFunction",
    "ApproximateNumericLiteral",
    "ValueExpression",
    "Where",
  };
}
