/* Generated By: AdqlStoX.jjt,v 1.33.2.4 2006-12-19 14&JJTree: Do not edit this line. AST_Term.java */

package org.astrogrid.adql;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.apache.xmlbeans.XmlObject;
import org.astrogrid.adql.v1_0.beans.BinaryExprType;
import org.astrogrid.adql.v1_0.beans.BinaryOperatorType;

public class AST_Term extends SimpleNode {
    
    private static Log log = LogFactory.getLog( AST_Term.class ) ;
    
    Token binaryOpToken ; 

    public AST_Term(AdqlStoX p, int id) {
        super(p, id);
    }

    public void setOperator( Token t ) {
        binaryOpToken = t ;
        getTracker().setType( BinaryExprType.type ) ;
        getTracker().push( AdqlCompiler.ARG_ELEMENT ) ;
    }
    
    public boolean isSetOperator() {
        return binaryOpToken != null ;
    }

    public void jjtClose() {
        if( isSetOperator() ) {
            getTracker().pop() ;
        }  
    }
    
    public void buildXmlTree( XmlObject xo ) {
        if( log.isTraceEnabled() ) enterTrace( log, "AST_Term.buildXmlTree()" ) ; 
        int childCount = jjtGetNumChildren() ;
        StringBuffer buffer = null ;
        if( log.isDebugEnabled() ) {
            buffer = new StringBuffer() ;
            buffer
                .append( "childCount: ") 
                .append( childCount ) ;         
        }
        if( isSetOperator() == false ) {
            children[0].buildXmlTree( xo ) ;
            this.generatedObject = children[0].getGeneratedObject() ;
        }
        else {
            BinaryExprType beType = (BinaryExprType)xo.changeType( BinaryExprType.type ) ;
            beType.setOper( BinaryOperatorType.Enum.forString( binaryOpToken.image ) ) ;
            if( log.isDebugEnabled() ) {
                buffer
                    .append( "\nbinaryOpToken: " )
                    .append( binaryOpToken.image ) ;
            }
            for( int i=0; i<childCount; i++ ) {
                children[i].buildXmlTree( beType.addNewArg() ) ;
                if( log.isDebugEnabled() ) {
                    buffer
                        .append( "\narg" ) 
                        .append( i )
                        .append( ": \n" )
                        .append( beType.getArgArray(i) ) ;
                }
            }
            setGeneratedObject( beType ) ;
        }
        
        if( log.isDebugEnabled() ) {
            log.debug( buffer.toString() ) ;
        }
        super.buildXmlTree( (XmlObject)this.generatedObject ) ;
        if( log.isTraceEnabled() ) exitTrace( log, "AST_Term.buildXmlTree()" ) ; 
    }

}
