<?xml version="1.0"?>
<definitions    name="DatasetAgentService"
                targetNameSpace="http//www.astrogrid.org/wsdl/DatasetAgent.wsdl"
                xmlns="http//schemas.xmlsoap.org/wsdl/"
                xmlns:soap="http//schemas.xmlsoap.org/wsdl/soap"
                xmlns:tns="http//www.astrogrid.org/wsdl/DatasetAgent.wsdl"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema">

        <message name="runQueryRequest">
                <part name="jobXML" type="xsd:string"/>
        </message>
        <message name="runQueryResponse">
                <part name="jobXML" type="xsd:string"/>
        </message>

        <portType name="DatasetAgentPortType">
                <operation name="runQuery">
                        <input message="tns:runQueryRequest" />
                        <output message="tns:runQueryResponse" />
                </operation>
        </portType>

        <binding name="DatasetAgentBinding" type="tns:DatasetAgentPortType">
                <soap:binding style ="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        </binding>

        <service name="DatasetAgentService"> 
                <port binding="tns:DatasetAgentBinding" name="DatasetAgentPortType">
                <documentation>The DatasetAgentService is the interface whereby jobs (queries at present) 
                are actually submitted for running at a specific data center. 
                </documentation>
                <soap:address location="http://hydra.star.le.ac.uk:8080/axis/services/DatasetAgent">
        </service>
</definitions>
