<?xml version="1.0" encoding="UTF-8"?>

<!--
Created on Mar 26, 2004
SEC WSDL
Nathan Ching nc@mssl.ucl.ac.uk 
-->

<definitions name="SEC"
  targetNamespace="urn:org.egso.sec/wsdl"
  xmlns:tns="urn:org.egso.sec/wsdl"
  xmlns="http://schemas.xmlsoap.org/wsdl/"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  
  <types/>
  
  <message name="SEC_sql">
    <part name="String_1" type="xsd:string"/>
  </message>
  
  <message name="SEC_sqlResponse">
    <part name="result" type="xsd:string"/>
  </message>
  
  <portType name="SEC">
    <operation name="sql" parameterOrder="String_1">
      <input message="tns:SEC_sql"/>
      <output message="tns:SEC_sqlResponse"/>
    </operation>
  </portType>
  
  <binding name="SECBinding" type="tns:SEC">
    <operation name="sql">
      <input>
        <soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
          use="encoded" namespace="urn:org.egso.sec/wsdl"/>
      </input>
      <output>
        <soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
          use="encoded" namespace="urn:org.egso.sec/wsdl"/>
        </output>
      <soap:operation soapAction=""/>
    </operation>
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"
      style="rpc"/>
  </binding>
  
  <service name="SEC">
    <port name="SECPort" binding="tns:SECBinding">
      <soap:address location="http://radiosun.ts.astro.it/sec/sec_server.php"/>
    </port>
  </service>

</definitions>
