/*
 * $Id: DataType.java,v 1.2 2011/09/13 13:43:26 pah Exp $
 * Copyright 2011 Paul Harrison (paul.harrison@manchester.ac.uk)
 *
 * File originally generated by JAXB, but since hand updated
 */


package net.ivoa.resource.dataservice;

import static javax.persistence.GenerationType.AUTO;
import static javax.persistence.InheritanceType.SINGLE_TABLE;

import java.util.HashMap;
import java.util.Map;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;
import javax.persistence.DiscriminatorColumn;


/**
 * 
 *             This XML type is used as a parent for defining data types
 *             with a restricted set of names.
 *          
 * 
 * <p>Java class for DataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DataType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>token">
 *       &lt;attribute name="arraysize" type="{http://www.ivoa.net/xml/VODataService/v1.1}ArrayShape" default="1" />
 *       &lt;attribute name="delim" type="{http://www.w3.org/2001/XMLSchema}string" default=" " />
 *       &lt;attribute name="extendedSchema" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="extendedType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DataType", propOrder = {
    "value"
})
@Entity
@Inheritance(strategy = SINGLE_TABLE)
@javax.persistence.Table(name="DataType")
@DiscriminatorColumn(name = "KIND")
public class DataType {

    @XmlTransient
    @Id
    @GeneratedValue(strategy = AUTO)
    int id;
    
    @XmlValue
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String value;
    
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String arraysize;
    
    @XmlAttribute
    protected String delim;
    
    @XmlAttribute
    protected String extendedSchema;
    
    @XmlAttribute
    protected String extendedType;
    
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the arraysize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArraysize() {
        if (arraysize == null) {
            return "1";
        } else {
            return arraysize;
        }
    }

    /**
     * Sets the value of the arraysize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArraysize(String value) {
        this.arraysize = value;
    }

    /**
     * Gets the value of the delim property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDelim() {
        if (delim == null) {
            return " ";
        } else {
            return delim;
        }
    }

    /**
     * Sets the value of the delim property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDelim(String value) {
        this.delim = value;
    }

    /**
     * Gets the value of the extendedSchema property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtendedSchema() {
        return extendedSchema;
    }

    /**
     * Sets the value of the extendedSchema property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtendedSchema(String value) {
        this.extendedSchema = value;
    }

    /**
     * Gets the value of the extendedType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtendedType() {
        return extendedType;
    }

    /**
     * Sets the value of the extendedType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtendedType(String value) {
        this.extendedType = value;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * 
     * <p>
     * the map is keyed by the name of the attribute and 
     * the value is the string value of the attribute.
     * 
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     * 
     * 
     * @return
     *     always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }

}
