/*
 * $Id: ObjectFactory.java,v 1.2 2011/09/13 13:43:26 pah Exp $
 * Copyright 2011 Paul Harrison (paul.harrison@manchester.ac.uk)
 *
 * File originally generated by JAXB, but since hand updated
 */


package net.ivoa.resource.dataservice;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the net.ivoa.resource.dataservice package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */

@XmlRegistry
public class ObjectFactory {

    private final static QName _TableParamFlag_QNAME = new QName("", "flag");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.ivoa.resource.dataservice
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TAPType }.
     * 
     */
    public TAPType createTAPType() {
        return new TAPType();
    }

    /**
     * Create an instance of {@link FKColumn }.
     * 
     */
    public FKColumn createFKColumn() {
        return new FKColumn();
    }

    /**
     * Create an instance of {@link CatalogService }.
     * 
     */
    public CatalogService createCatalogService() {
        return new CatalogService();
    }

    /**
     * Create an instance of {@link Format }.
     * 
     */
    public Format createFormat() {
        return new Format();
    }

    /**
     * Create an instance of {@link DataService }.
     * 
     */
    public DataService createDataService() {
        return new DataService();
    }

    /**
     * Create an instance of {@link VOTableType }.
     * 
     */
    public VOTableType createVOTableType() {
        return new VOTableType();
    }

    /**
     * Create an instance of {@link DataCollection }.
     * 
     */
    public DataCollection createDataCollection() {
        return new DataCollection();
    }

    /**
     * Create an instance of {@link TableSet }.
     * 
     */
    public TableSet createTableSet() {
        return new TableSet();
    }

    /**
     * Create an instance of {@link TableSchema }.
     * 
     */
    public TableSchema createTableSchema() {
        return new TableSchema();
    }

    /**
     * Create an instance of {@link Table }.
     * 
     */
    public Table createTable() {
        return new Table();
    }

    /**
     * Create an instance of {@link TableParam }.
     * 
     */
    public TableParam createTableParam() {
        return new TableParam();
    }

    /**
     * Create an instance of {@link ServiceReference }.
     * 
     */
    public ServiceReference createServiceReference() {
        return new ServiceReference();
    }

    /**
     * Create an instance of {@link InputParam }.
     * 
     */
    public InputParam createInputParam() {
        return new InputParam();
    }

    /**
     * Create an instance of {@link ForeignKey }.
     * 
     */
    public ForeignKey createForeignKey() {
        return new ForeignKey();
    }

    /**
     * Create an instance of {@link Coverage }.
     * 
     */
    public Coverage createCoverage() {
        return new Coverage();
    }

    /**
     * Create an instance of {@link ParamHTTP }.
     * 
     */
    public ParamHTTP createParamHTTP() {
        return new ParamHTTP();
    }

    /**
     * Create an instance of {@link StandardSTC }.
     * 
     */
    public StandardSTC createStandardSTC() {
        return new StandardSTC();
    }

    /**
     * Create an instance of {@link DataType }.
     * 
     */
    public DataType createDataType() {
        return new DataType();
    }

    /**
     * Create an instance of {@link BaseParam }.
     * 
     */
    public BaseParam createBaseParam() {
        return new BaseParam();
    }

    /**
     * Create an instance of {@link SimpleDataType }.
     * 
     */
    public SimpleDataType createSimpleDataType() {
        return new SimpleDataType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}.
     * 
     */
    @XmlElementDecl(namespace = "", name = "flag", scope = TableParam.class)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createTableParamFlag(String value) {
        return new JAXBElement<String>(_TableParamFlag_QNAME, String.class, TableParam.class, value);
    }

}
