//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.06.16 at 04:47:20 PM BST 
//


package net.ivoa.resource.dataservice;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the net.ivoa.resource.dataservice package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.ivoa.resource.dataservice
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Table }
     * 
     */
    public Table createTable() {
        return new Table();
    }

    /**
     * Create an instance of {@link RelationalJoin }
     * 
     */
    public RelationalJoin createRelationalJoin() {
        return new RelationalJoin();
    }

    /**
     * Create an instance of {@link BaseParam }
     * 
     */
    public BaseParam createBaseParam() {
        return new BaseParam();
    }

    /**
     * Create an instance of {@link SimpleDataType }
     * 
     */
    public SimpleDataType createSimpleDataType() {
        return new SimpleDataType();
    }

    /**
     * Create an instance of {@link Function }
     * 
     */
    public Function createFunction() {
        return new Function();
    }

    /**
     * Create an instance of {@link Format }
     * 
     */
    public Format createFormat() {
        return new Format();
    }

    /**
     * Create an instance of {@link DataCollection }
     * 
     */
    public DataCollection createDataCollection() {
        return new DataCollection();
    }

    /**
     * Create an instance of {@link TableParam }
     * 
     */
    public TableParam createTableParam() {
        return new TableParam();
    }

    /**
     * Create an instance of {@link TableService }
     * 
     */
    public TableService createTableService() {
        return new TableService();
    }

    /**
     * Create an instance of {@link Coverage }
     * 
     */
    public Coverage createCoverage() {
        return new Coverage();
    }

    /**
     * Create an instance of {@link StandardSTC }
     * 
     */
    public StandardSTC createStandardSTC() {
        return new StandardSTC();
    }

    /**
     * Create an instance of {@link RelationalSchema }
     * 
     */
    public RelationalSchema createRelationalSchema() {
        return new RelationalSchema();
    }

    /**
     * Create an instance of {@link TableDataType }
     * 
     */
    public TableDataType createTableDataType() {
        return new TableDataType();
    }

    /**
     * Create an instance of {@link InputParam }
     * 
     */
    public InputParam createInputParam() {
        return new InputParam();
    }

    /**
     * Create an instance of {@link DataService }
     * 
     */
    public DataService createDataService() {
        return new DataService();
    }

    /**
     * Create an instance of {@link CatalogService }
     * 
     */
    public CatalogService createCatalogService() {
        return new CatalogService();
    }

    /**
     * Create an instance of {@link RelationalJoin.ColumnPair }
     * 
     */
    public RelationalJoin.ColumnPair createRelationalJoinColumnPair() {
        return new RelationalJoin.ColumnPair();
    }

    /**
     * Create an instance of {@link Catalog }
     * 
     */
    public Catalog createCatalog() {
        return new Catalog();
    }

    /**
     * Create an instance of {@link ServiceReference }
     * 
     */
    public ServiceReference createServiceReference() {
        return new ServiceReference();
    }

    /**
     * Create an instance of {@link ParamHTTP }
     * 
     */
    public ParamHTTP createParamHTTP() {
        return new ParamHTTP();
    }

}
