ln ../../style/astrogrid.css
ln ../../style/calculator.css
ln ../../style/csshover.htc
ln ../../style/footer_ag.xml
ln ../../style/footer_helio.xml
ln ../../style/footer_vamdc.xml
ln ../../style/footer.xml
ln ../../style/handle.horizontal.png
ln ../../style/header_ag.xml
ln ../../style/header_helio.xml
ln ../../style/header_vamdc.xml
ln ../../style/header.xml
ln ../../style/ivoa.css
ln ../../style/link_options.xml
ln ../../style/navigation.xml
ln ../../style/source.css
ln ../../style/styles.css
ln ../../style/styleswitcher.js
ln ../../style/xforms.css
