/* Generated by Together */

public class RegistrationService {

    private Connection conn = CommunityDB.getConnection();
    
       public boolean createAccount(String me, String who) {

    }


}
