/* Generated by Together */

package org.astrogrid.datacenter;

public class JobException extends java.lang.Exception {
	
    public JobException() {
    	super() ;
    }

    public JobException( String message ) {
		super( message ) ;
    }

    public JobException( Exception exception ) {
		super( exception ) ;
    }

    public JobException( String message, Exception exception ) {
		super( message, exception ) ;
    }
    
}
