/* Generated by Together */

package org.astrogrid.datacenter;

public interface MySpaceFactory {
	
    public Allocation allocateCacheSpace(String jobURN, int size) throws AllocationException ;
    
    public void close( Allocation allocation ) throws AllocationException ;
    
    
}
