/*
 * $Id: ApplicationCapability.java,v 1.2 2011/09/13 13:43:32 pah Exp $
 * Copyright 2011 Paul Harrison (paul.harrison@manchester.ac.uk)
 *
 * File originally generated by JAXB, but since hand updated
 */


package net.ivoa.resource.applications;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *             generic description of a capability of an application - this
 *             is different from a service capability because it does not
 *             have an interface associated - perhaps should be derived
 *             from a common base class though.
 *          
 * 
 * <p>Java class for ApplicationCapability complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ApplicationCapability">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="standardID" type="{http://www.ivoa.net/xml/VOResource/v1.0}IdentifierURI" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ApplicationCapability")
public class ApplicationCapability {

    @XmlAttribute
    protected String standardID;

    /**
     * Gets the value of the standardID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStandardID() {
        return standardID;
    }

    /**
     * Sets the value of the standardID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStandardID(String value) {
        this.standardID = value;
    }

}
