/*
 * $Id: DataFormatDirection.java,v 1.2 2011/09/13 13:43:32 pah Exp $
 * Copyright 2011 Paul Harrison (paul.harrison@manchester.ac.uk)
 *
 * File originally generated by JAXB, but since hand updated
 */


package net.ivoa.resource.applications;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;


/**
 * <p>Java class for DataFormatDirection.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DataFormatDirection">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="read"/>
 *     &lt;enumeration value="write"/>
 *     &lt;enumeration value="both"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum DataFormatDirection {

    @XmlEnumValue("read")
    READ("read"),
    @XmlEnumValue("write")
    WRITE("write"),
    @XmlEnumValue("both")
    BOTH("both");
    private final String value;

    DataFormatDirection(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DataFormatDirection fromValue(String v) {
        for (DataFormatDirection c: DataFormatDirection.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v.toString());
    }

}
