/*
 $Id: AceConsumer.java,v 1.1.1.1 2003/08/25 18:36:02 mch Exp $

 (c) Copyright...
 */


package org.astrogrid.ace.client;

import java.io.InputStream;

/**
 * Applications that want to use ACE, such as Aladin, will tend to want ACE
 * to display the dialog box modally, and then go off and get the results
 * asynchronously.
 * <p>
 * This class provides that callback mechanism.  The calling application implements
 * it (or provides an implementation of it), calls AceProducer with a reference to it, and
 * ACE then calls the <code>consumeAceResults()</code> method with the votable as
 * an InputStream
 * <P>
 * NB - the method to be implemented here is likely to be called by a separate extraction
 * thread generated by ACE, so watch out for synchronisation issues.
 * <p>
 * Implementation point - <code>VotConsumer</code> is the default consumer for
 * ACE, which provides the VOTable as an XML document (ie DOM node) rather than
 * as an InputStream.  So to use this interface, call AceProducer with an implementation
 * of this class. AceProducer uses <code>VOT2InputPipe</code>
 * to do the conversion.
 */

public interface AceConsumer
{
   public void consumeAceResults(InputStream results);
}


/*
$Log: AceConsumer.java,v $
Revision 1.1.1.1  2003/08/25 18:36:02  mch
Reimported to fit It02 source structure

Revision 1.2  2003/07/11 10:41:22  mch
Added javadoc explanation

Revision 1.1  2003/06/18 15:59:51  mch
Introdueced to remove circular dependency with Aladin

*/

