//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.06.18 at 08:28:07 PM BST 
//


package org.astrogrid.applications.description.impl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.astrogrid.applications.description.base.ApplicationBase;


/**
 * 
 *             Description of a command line application
 *          
 * 
 * <p>Java class for CeaCmdLineApplicationDefinition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CeaCmdLineApplicationDefinition">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ivoa.net/xml/CEA/base/v1.1}ApplicationBase">
 *       &lt;sequence>
 *         &lt;element name="executionPath" type="{http://www.astrogrid.org/schema/CEAImplementation/v2.0}ExecutableDescription"/>
 *       &lt;/sequence>
 *       &lt;attribute name="instanceClass" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CeaCmdLineApplicationDefinition", propOrder = {
    "executionPath"
})
@XmlRootElement
public class CeaCmdLineApplicationDefinition
    extends ApplicationBase
{

    @XmlElement(required = true)
    protected ExecutableDescription executionPath;
    @XmlAttribute
    protected String instanceClass;

    /**
     * Gets the value of the executionPath property.
     * 
     * @return
     *     possible object is
     *     {@link ExecutableDescription }
     *     
     */
    public ExecutableDescription getExecutionPath() {
        return executionPath;
    }

    /**
     * Sets the value of the executionPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExecutableDescription }
     *     
     */
    public void setExecutionPath(ExecutableDescription value) {
        this.executionPath = value;
    }

    /**
     * Gets the value of the instanceClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstanceClass() {
        return instanceClass;
    }

    /**
     * Sets the value of the instanceClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstanceClass(String value) {
        this.instanceClass = value;
    }

}
