//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.06.18 at 08:28:07 PM BST 
//


package org.astrogrid.applications.description.impl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import net.ivoa.resource.dataservice.DataService;
import org.astrogrid.applications.description.base.ApplicationBase;


/**
 * 
 *            Definition of a general DAL style service served by a CEA
 *            server. Includes possibility of specifying
 *            ApplicationDefinition - parameters Coverage desired outputs
 *            Capabilities - but only need to put in the standardId - the
 *            other things will be filled in automatically
 *         
 * 
 * <p>Java class for CEADALService complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CEADALService">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ivoa.net/xml/VODataService/v1.1}DataService">
 *       &lt;sequence>
 *         &lt;element name="applicationDefinition" type="{http://www.ivoa.net/xml/CEA/base/v1.1}ApplicationBase"/>
 *       &lt;/sequence>
 *       &lt;attribute name="publishApplication" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CEADALService", propOrder = {
    "applicationDefinition"
})
public class CEADALService
    extends DataService
{

    @XmlElement(required = true)
    protected ApplicationBase applicationDefinition;
    @XmlAttribute
    protected Boolean publishApplication;

    /**
     * Gets the value of the applicationDefinition property.
     * 
     * @return
     *     possible object is
     *     {@link ApplicationBase }
     *     
     */
    public ApplicationBase getApplicationDefinition() {
        return applicationDefinition;
    }

    /**
     * Sets the value of the applicationDefinition property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApplicationBase }
     *     
     */
    public void setApplicationDefinition(ApplicationBase value) {
        this.applicationDefinition = value;
    }

    /**
     * Gets the value of the publishApplication property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isPublishApplication() {
        if (publishApplication == null) {
            return false;
        } else {
            return publishApplication;
        }
    }

    /**
     * Sets the value of the publishApplication property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPublishApplication(Boolean value) {
        this.publishApplication = value;
    }

}
