//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.06.18 at 08:28:07 PM BST 
//


package org.astrogrid.applications.description.impl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import net.ivoa.resource.cea.CeaApplication;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded">
 *           &lt;element ref="{http://www.astrogrid.org/schema/CEAImplementation/v2.0}CeaApplication"/>
 *           &lt;element ref="{http://www.astrogrid.org/schema/CEAImplementation/v2.0}CeaDALService"/>
 *           &lt;element ref="{http://www.astrogrid.org/schema/CEAImplementation/v2.0}DBDefinition"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ceaApplicationOrCeaDALServiceOrDBDefinition"
})
@XmlRootElement(name = "CECConfig")
public class CECConfig {

    @XmlElements({
        @XmlElement(name = "CeaDALService", namespace = "http://www.astrogrid.org/schema/CEAImplementation/v2.0", type = CEADALService.class),
        @XmlElement(name = "DBDefinition", namespace = "http://www.astrogrid.org/schema/CEAImplementation/v2.0", type = DBDefinition.class),
        @XmlElement(name = "CeaApplication", namespace = "http://www.astrogrid.org/schema/CEAImplementation/v2.0", type = CeaApplication.class)
    })
    protected List<Object> ceaApplicationOrCeaDALServiceOrDBDefinition;

    /**
     * Gets the value of the ceaApplicationOrCeaDALServiceOrDBDefinition property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ceaApplicationOrCeaDALServiceOrDBDefinition property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCeaApplicationOrCeaDALServiceOrDBDefinition().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CEADALService }
     * {@link DBDefinition }
     * {@link CeaApplication }
     * 
     * 
     */
    public List<Object> getCeaApplicationOrCeaDALServiceOrDBDefinition() {
        if (ceaApplicationOrCeaDALServiceOrDBDefinition == null) {
            ceaApplicationOrCeaDALServiceOrDBDefinition = new ArrayList<Object>();
        }
        return this.ceaApplicationOrCeaDALServiceOrDBDefinition;
    }

}
