//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.06.10 at 03:44:35 PM BST 
//


package net.ivoa.resource.sia;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the net.ivoa.resource.sia package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.ivoa.resource.sia
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SimpleImageAccess }
     * 
     */
    public SimpleImageAccess createSimpleImageAccess() {
        return new SimpleImageAccess();
    }

    /**
     * Create an instance of {@link SkySize }
     * 
     */
    public SkySize createSkySize() {
        return new SkySize();
    }

    /**
     * Create an instance of {@link SkyPos }
     * 
     */
    public SkyPos createSkyPos() {
        return new SkyPos();
    }

    /**
     * Create an instance of {@link ImageSize }
     * 
     */
    public ImageSize createImageSize() {
        return new ImageSize();
    }

    /**
     * Create an instance of {@link Query }
     * 
     */
    public Query createQuery() {
        return new Query();
    }

}
