//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.06.10 at 03:44:35 PM BST 
//


package net.ivoa.resource.sia;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *             Editor's Notes: 
 *                *  This is a prototype definition to
 *                   illustrate how to extend the schema to a specific 
 *                   standard interface.
 *                *  Staging information is not included yet.   
 *          
 * 
 * <p>Java class for SimpleImageAccess complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SimpleImageAccess">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ivoa.net/xml/SIA/v1.0}SIACapRestriction">
 *       &lt;sequence>
 *         &lt;element name="imageServiceType" type="{http://www.ivoa.net/xml/SIA/v1.0}ImageServiceType"/>
 *         &lt;element name="maxQueryRegionSize" type="{http://www.ivoa.net/xml/SIA/v1.0}SkySize"/>
 *         &lt;element name="maxImageExtent" type="{http://www.ivoa.net/xml/SIA/v1.0}SkySize"/>
 *         &lt;element name="maxImageSize" type="{http://www.ivoa.net/xml/SIA/v1.0}ImageSize"/>
 *         &lt;element name="maxFileSize" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="maxRecords" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="testQuery" type="{http://www.ivoa.net/xml/SIA/v1.0}Query" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SimpleImageAccess", propOrder = {
    "imageServiceType",
    "maxQueryRegionSize",
    "maxImageExtent",
    "maxImageSize",
    "maxFileSize",
    "maxRecords",
    "testQuery"
})
public class SimpleImageAccess
    extends SIACapRestriction
{

    @XmlElement(required = true)
    protected ImageServiceType imageServiceType;
    @XmlElement(required = true)
    protected SkySize maxQueryRegionSize;
    @XmlElement(required = true)
    protected SkySize maxImageExtent;
    @XmlElement(required = true)
    protected ImageSize maxImageSize;
    protected int maxFileSize;
    protected int maxRecords;
    protected Query testQuery;

    /**
     * Gets the value of the imageServiceType property.
     * 
     * @return
     *     possible object is
     *     {@link ImageServiceType }
     *     
     */
    public ImageServiceType getImageServiceType() {
        return imageServiceType;
    }

    /**
     * Sets the value of the imageServiceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImageServiceType }
     *     
     */
    public void setImageServiceType(ImageServiceType value) {
        this.imageServiceType = value;
    }

    /**
     * Gets the value of the maxQueryRegionSize property.
     * 
     * @return
     *     possible object is
     *     {@link SkySize }
     *     
     */
    public SkySize getMaxQueryRegionSize() {
        return maxQueryRegionSize;
    }

    /**
     * Sets the value of the maxQueryRegionSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link SkySize }
     *     
     */
    public void setMaxQueryRegionSize(SkySize value) {
        this.maxQueryRegionSize = value;
    }

    /**
     * Gets the value of the maxImageExtent property.
     * 
     * @return
     *     possible object is
     *     {@link SkySize }
     *     
     */
    public SkySize getMaxImageExtent() {
        return maxImageExtent;
    }

    /**
     * Sets the value of the maxImageExtent property.
     * 
     * @param value
     *     allowed object is
     *     {@link SkySize }
     *     
     */
    public void setMaxImageExtent(SkySize value) {
        this.maxImageExtent = value;
    }

    /**
     * Gets the value of the maxImageSize property.
     * 
     * @return
     *     possible object is
     *     {@link ImageSize }
     *     
     */
    public ImageSize getMaxImageSize() {
        return maxImageSize;
    }

    /**
     * Sets the value of the maxImageSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImageSize }
     *     
     */
    public void setMaxImageSize(ImageSize value) {
        this.maxImageSize = value;
    }

    /**
     * Gets the value of the maxFileSize property.
     * 
     */
    public int getMaxFileSize() {
        return maxFileSize;
    }

    /**
     * Sets the value of the maxFileSize property.
     * 
     */
    public void setMaxFileSize(int value) {
        this.maxFileSize = value;
    }

    /**
     * Gets the value of the maxRecords property.
     * 
     */
    public int getMaxRecords() {
        return maxRecords;
    }

    /**
     * Sets the value of the maxRecords property.
     * 
     */
    public void setMaxRecords(int value) {
        this.maxRecords = value;
    }

    /**
     * Gets the value of the testQuery property.
     * 
     * @return
     *     possible object is
     *     {@link Query }
     *     
     */
    public Query getTestQuery() {
        return testQuery;
    }

    /**
     * Sets the value of the testQuery property.
     * 
     * @param value
     *     allowed object is
     *     {@link Query }
     *     
     */
    public void setTestQuery(Query value) {
        this.testQuery = value;
    }

}
