/* Generated by Together */

package org.astrogrid.datacenter.impl;

import org.astrogrid.datacenter.MySpaceFactory;
import org.astrogrid.datacenter.Allocation;
import org.astrogrid.datacenter.AllocationException;
public class MySpaceFactoryImpl implements MySpaceFactory {
    public Allocation allocateCacheSpace(String jobID, int size) throws AllocationException { 
       return new Allocation() ;
    }
}
