#!/usr/bin/env python
# List all jobs for this user.
# usage : jobs-list
# return : list of jobURNs
import xmlrpclib as x
import sys
import os
prefix = file(os.path.expanduser("~/.astrogrid-desktop")).next().rstrip()
s = x.Server(prefix + "xmlrpc")
for urn in s.astrogrid.jobs.list() :
        print urn