#!/usr/bin/env python
# retreive a transcript or summary for a job
# usage : jobs-get [--summary] <job-urn>
# return : xml document of job transcript, or text summary
# option : --summary - return a summary of the job. otherwise return the whole transcript.
import xmlrpclib as x
import sys
import os
prefix = file(os.path.expanduser("~/.astrogrid-desktop")).next().rstrip()
s = x.Server(prefix + "xmlrpc")
if len(sys.argv) > 2 and (sys.argv[1] == "--summary" or sys.argv[1] == "-s"):
 print s.astrogrid.jobs.getJobSummary(sys.argv[2])
else :
 print s.astrogrid.jobs.getJob(sys.argv[1])

