#!/usr/bin/env python
# List registered applications
# usage : lsapps [-a|--all]
# return : list of application names
# option : [-a | --all] - return fuller descriptions of applications
import xmlrpclib as x
import sys
import os
prefix = file(os.path.expanduser("~/.astrogrid-desktop")).next().rstrip()
s = x.Server(prefix + "xmlrpc")
if len(sys.argv) > 1 and (sys.argv[1] == "--all" or sys.argv[1] == "-a"):
 for i in s.astrogrid.applications.fullList():
  print i
else :
 for i in s.astrogrid.applications.list():
  print i

