#!/usr/bin/env python
# retreive a named record from the registry
# usage: reg [--summary] <ivorn>
# return : xml document, or summary, of registry entry
# example reg uk.ac.le.star/filemanager
import xmlrpclib as x
import sys
import os
prefix = file(os.path.expanduser("~/.astrogrid-desktop")).next().rstrip()
s = x.Server(prefix + "xmlrpc")
if len(sys.argv) > 2 and (sys.argv[1] == "-s" or sys.argv[1] == "--summary"):
	print s.astrogrid.registry.getResourceData(sys.argv[2])
else
	print s.astrogrid.registry.getRecord(sys.argv[1])