#!/usr/bin/env python
# retreive a named record from the registry
# usage: reg <ivorn>
# return : xml document of registry entry
# example reg uk.ac.le.star/filemanager
import xmlrpclib as x
import sys
import os
prefix = file(os.path.expanduser("~/.astrogrid-desktop")).next().rstrip()
s = x.Server(prefix + "xmlrpc")
print s.astrogrid.registry.getRecord(sys.argv[1])