#!/usr/bin/env python
# perform a full registry query
# usage : reg-search <query string of SADQL>
# return : xml document of results.
import xmlrpclib as x
import sys
import os
prefix = file(os.path.expanduser("~/.astrogrid-desktop")).next().rstrip()
s = x.Server(prefix + "xmlrpc")
print s.astrogrid.registry.search(sys.argv[1])