#!/usr/bin/env python
# write data to a vospace resource
# usage voput <local-file> <vospace-ivorn> 
import xmlrpclib as x
import sys
import os
import os.path
import urlparse

prefix = file(os.path.expanduser("~/.astrogrid-desktop")).next().rstrip()
s = x.Server(prefix + "xmlrpc")
ivorn = sys.argv[2]
if not (ivorn[0:4] == 'ivo:') :
	ivorn = s.astrogrid.myspace.home() + "/" + ivorn

# build url from local file reference.
f = file(sys.argv[1])
url = urlparse.urlunsplit(["file","",os.path.abspath(f.name),"",""])

# create node if needed.
if not s.astrogrid.myspace.exists(ivorn):
	parent = ivorn[0:ivorn.rfind("/")]
	name = ivorn[ivorn.rfind("/")+1:]
	s.astrogrid.myspace.newFile(parent,name)
	
s.astrogrid.myspace.copyURLToContent(url,ivorn)

