#!/usr/bin/env python
# write data to a vospace resource
# usage voput <vospace-ivorn> <local-file>
import xmlrpclib as x
import sys
import os
import urlparse
#NB - found the vospace api quite uncomfortable for doing this - need to take a fresh look at it.

prefix = file(os.path.expanduser("~/.astrogrid-desktop")).next().rstrip()
s = x.Server(prefix + "xmlrpc")

ivorn = sys.argv[1]
# build url from local file reference.
f = file(sys.argv[2])
url = urlparse.urlunsplit(["file","",f.name,"",""])

# create node if needed.
if not s.astrogrid.vospace.exists(ivorn):
        # can't do much here - need a api method to creeate new ivorn.
        #n = s.astrogrid.myspace.newFile(
else :
        s.astrogrid.myspace.copyURLToContent(url,ivorn)

