#!/usr/bin/env python
# delete a vospace file
# usage : vorm <vospace-ivorn>
import xmlrpclib as x
import sys
import os
prefix = file(os.path.expanduser("~/.astrogrid-desktop")).next().rstrip()
s = x.Server(prefix + "xmlrpc")
print s.astrogrid.vospace.delete(sys.argv[1])
