#!/usr/bin/env python
# delete a vospace file
# usage : vorm <vospace-ivorn>
import xmlrpclib as x
import sys
import os
prefix = file(os.path.expanduser("~/.astrogrid-desktop")).next().rstrip()
s = x.Server(prefix + "xmlrpc")
ivorn = sys.argv[1]
if not (ivorn[0:4] == 'ivo:') :
	ivorn = s.astrogrid.myspace.home() + "/" + ivorn
print s.astrogrid.myspace.delete(ivorn)
