<?xml version="1.0"?> 
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0">
	<xsl:output method="text" indent="no" omit-xml-declaration="yes"/>
	<xsl:strip-space elements="*"/>

<!-- ============== VARIABLES ============== -->

<xsl:variable name="newline">
<xsl:text>
</xsl:text>
</xsl:variable>

<xsl:variable name="spaces">
<xsl:text>    </xsl:text>
</xsl:variable>

<!-- ============== TEMPLATES ============== -->

<!-- START OF DOCUMENT -->
<xsl:template match="/">
	<xsl:text># Generated by org.astrogrid.ace.utils - XSLT implementation</xsl:text>
	<xsl:value-of select="$newline"/>
	<xsl:text>#!WARNING! - This interim release does not support vector parameters,</xsl:text>
	<xsl:value-of select="$newline"/>
	<xsl:text>#   eg MAG_APER(3), VIGNET(2,4) etc.</xsl:text>
	<xsl:value-of select="$newline"/>
<!-- SUPPRESS OUTPUT - JUST CONTINUE DOWN -->
   <xsl:apply-templates/>
</xsl:template>


<!-- TOPLEVEL (ROOT) NODE - AceInputDoc -->
<xsl:template match="*">
<!-- SUPPRESS OUTPUT - JUST CONTINUE DOWN -->
   <xsl:apply-templates/>
</xsl:template>


<!-- TAGS WITHIN TOPLEVEL (ROOT) NODE -->
<xsl:template match="*/*">

	<xsl:choose>

		<xsl:when test="(name(.)='OUTPUT_COLUMNS')">
			<xsl:for-each select="arg">
				<xsl:choose>
					<!-- VECTOR PARAMS - CAN'T DO THESE FOR NOW -->
					<xsl:when test="(.='FLUX_APER')
										or (.='FLUXERR_APER')
										or (.='MAG_APER')
										or (.='MAGERR_APER')
										or (.='VECTOR_SOMFIT')
										or (.='VECTOR_ASSOC')
										or (.='FLUX_GROWTH')
										or (.='VIGNET')
										or (.='VIGNET_SHIFT')">

						<xsl:text>#!WARNING! Vector parameter "</xsl:text>
						<xsl:value-of select="."/>  
						<xsl:text>" is not supported in this release!</xsl:text>
						<xsl:value-of select="$newline"/>
					</xsl:when>

					<!-- NON-VECTOR PARAMS - PROCESS AS NORMAL -->
					<xsl:otherwise>
						<xsl:value-of select="."/>  
						<xsl:value-of select="$newline"/>
					</xsl:otherwise>

				</xsl:choose>
			</xsl:for-each>
		</xsl:when>

		<!-- CONFIG OR COMMAND-LINE PARAMETERS - IGNORE -->
		<xsl:otherwise>
			<!-- SUPPRESS OUTPUT AND IGNORE -->
		</xsl:otherwise>

	</xsl:choose>
</xsl:template>

</xsl:stylesheet>
