<?xml version="1.0"?> 
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0">
	<xsl:output method="text" indent="no" omit-xml-declaration="yes"/>
	<xsl:strip-space elements="*"/>

<!-- ============== VARIABLES ============== -->

<xsl:variable name="newline">
<xsl:text>
</xsl:text>
</xsl:variable>

<xsl:variable name="spaces">
<xsl:text>    </xsl:text>
</xsl:variable>

<!-- ============== TEMPLATES ============== -->

<!-- START OF DOCUMENT -->
<xsl:template match="/">
	<xsl:text># Generated by org.astrogrid.ace.utils - XSLT implementation</xsl:text>
	<xsl:value-of select="$newline"/>
<!-- SUPPRESS OUTPUT - JUST CONTINUE DOWN -->
   <xsl:apply-templates/>
</xsl:template>


<!-- TOPLEVEL (ROOT) NODE - AceInputDoc -->
<xsl:template match="*">
<!-- SUPPRESS OUTPUT - JUST CONTINUE DOWN -->
   <xsl:apply-templates/>
</xsl:template>


<!-- TAGS WITHIN TOPLEVEL (ROOT) NODE -->
<xsl:template match="*/*">

	<xsl:choose>

		<!-- COMMAND LINE PARAMETERS - IGNORE -->
		<xsl:when test="(name(.)='ImageToCatalog') 
							or (name(.)='ImageToMeasure')
							or (name(.)='Wavelength')">
			<!-- SUPPRESS OUTPUT AND IGNORE -->
		</xsl:when>

		<!-- OUTPUT CATALOG PARAMETERS - IGNORE -->
		<xsl:when test="(name(.)='OUTPUT_COLUMNS')"> 
			<!-- SUPPRESS OUTPUT AND IGNORE -->
		</xsl:when>

		<!-- BOOLEAN SPECIAL CASES -->
		<xsl:when test="(name(.)='CLEAN') 
							or (name(.)='FILTER')
							or (name(.)='FITS_UNSIGNED')
							or (name(.)='WEIGHT_GAIN')">
			<xsl:value-of select="name(.)"/>  
			<xsl:value-of select="$spaces"/>
			<xsl:if test="arg='true'">
				<xsl:text>Y</xsl:text>
			</xsl:if>
			<xsl:if test="arg='false'">
				<xsl:text>N</xsl:text>
			</xsl:if>
			<xsl:value-of select="$newline"/>
		</xsl:when>

		<!-- ALL OTHER CASES -->
		<xsl:otherwise>
			<xsl:value-of select="name(.)"/>  
			<xsl:value-of select="$spaces"/>
			<xsl:for-each select="arg">
				<xsl:value-of select="."/>  
				<xsl:if test="following-sibling::arg"> 
					<xsl:text>, </xsl:text>
				</xsl:if>	
			</xsl:for-each>
			<xsl:value-of select="$newline"/>
		</xsl:otherwise>
	</xsl:choose>
</xsl:template>

</xsl:stylesheet>
