/*$Id: EgsoDelegate.java,v 1.3 2004/09/29 13:39:01 mch Exp $
 * Created on 16-Oct-2003
 *
 * Copyright (C) AstroGrid. All rights reserved.
 *
 * This software is published under the terms of the AstroGrid
 * Software License version 1.2, a copy of which has been included
 * with this distribution in the LICENSE.txt file.
 *
 **/
package org.astrogrid.datacenter.sec.secdelegate.egso;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.rpc.ServiceException;
import org.apache.axis.utils.XMLUtils;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.astrogrid.util.DomHelper;
import org.w3c.dom.Document;
import org.xml.sax.SAXException;

/** Delegate around the soap client generated by wsdl2java
 * @todo - refine the parameters to web methods - can lift from strings to enumerated constants (once we
 * find out what these constants are).
 * @author Noel Winstanley nw@jb.man.ac.uk 16-Oct-2003
 *
 */
public class EgsoDelegate {
   
   static Log log = LogFactory.getLog(EgsoDelegate.class);
   
   /** The SEC service endpoint */
   public static final String DEFAULT_SEC_ENDPOINT = "http://radiosun.ts.astro.it/sec/sec_server.php";
   
   /** WSDL-generated binding to the service */
   protected SEC_Port secPort;
   
   /** construct delegate connected to default service endpoint */
   public EgsoDelegate() throws ServiceException, MalformedURLException {
      this(new URL(DEFAULT_SEC_ENDPOINT));
   }
   /** construct a delegate connected to the specified endpoint */
   public EgsoDelegate(String endpoint) throws MalformedURLException, ServiceException {
      this(new URL(endpoint));
   }
   /** construct a delegate connected to the specified endpoint */
   public EgsoDelegate(URL endpoint) throws ServiceException {
      SEC_Service service = new SEC_ServiceLocator();
      secPort = service.getSECPort(endpoint);
   }
   
   /** Run given SQL on SEC service port, returning parsed Document of returned string */
   public Document doQuery(String sql)  throws ParserConfigurationException, SAXException, IOException {
      return DomHelper.newDocument(secPort.sql(sql));
   }
   
}


/*
 $Log: EgsoDelegate.java,v $
 Revision 1.3  2004/09/29 13:39:01  mch
 Removed obsolete ADQL 0.5

 Revision 1.2  2004/07/07 14:32:54  KevinBenson
 Few small changes because I had it referencing "cds" at the moment.

 Revision 1.1  2004/07/07 09:17:40  KevinBenson
 New SEC/EGSO proxy to query there web service on the Solar Event Catalog

 Revision 1.2  2003/12/01 16:50:30  nw
 first working tested version

 Revision 1.1  2003/10/16 10:11:45  nw
 first check in
 
 */
