<?xml version="1.0" encoding="UTF-8"?>
<definitions name="searchableRegistry" 
             xmlns="http://schemas.xmlsoap.org/wsdl/" 
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
             xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" 
             xmlns:ris="http://www.ivoa.net/wsdl/RegistrySearch/v0.1"
             xmlns:tns="http://www.astrogrid.org/registry/wsdl"
             targetNamespace="http://www.astrogrid.org/registry/wsdl">             
   <import namespace="http://www.ivoa.net/wsdl/RegistrySearch/v0.1"
           location="Search.wsdl"/>   <service xmlns:soap2="http://schemas.xmlsoap.org/wsdl/soap/"  name="RegistryInterfaceService">
      <port name="RegistrySearchPort" binding="ris:RegistrySearchSOAP">
         <soap:address 
        location="http://localhost:8080/astrogrid-registry/services/RegistrySearchPort"/>
      </port>   </service>
</definitions>