<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://www.example.com/webservice" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/"
 xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
 xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
 xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xmlns:ws="http://www.example.com/webservice">
	
	<wsdl:message name="whoAmIRequest"/>
	<wsdl:message name="whoAmIResponse">
		<wsdl:part name="identity" type="xs:string"/>
	</wsdl:message>
	
	<wsdl:portType name="SamplePortType">
		<wsdl:operation name="whoAmI">
			<wsdl:input message="whoAmIRequest"/>
			<wsdl:output message="whoAmIResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	
	<wsdl:binding type="SamplePortType" name="SamplePortSoapBinding">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="whoAmI">
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	
	<wsdl:service name="SampleService">
		<wsdl:port name="SamplePort" binding="SamplePortSoapBinding">
			<soap:address location="http://localhost:8080/security/services/Sample"/>
		</wsdl:port>
	</wsdl:service>
	
</wsdl:definitions>