<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://www.astrogrid.org/registry" xmlns:impl="http://www.astrogrid.org/registry" xmlns:intf="http://www.astrogrid.org/registry" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:types>
    <schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.astrogrid.org/registry">
      <import namespace="http://schemas.xmlsoap.org/soap/encoding/"/>
      <element name="process" type="xsd:anyType"/>
    </schema>
    <schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="">
      <import namespace="http://schemas.xmlsoap.org/soap/encoding/"/>
      <element name="processReturn" type="xsd:anyType"/>
    </schema>
  </wsdl:types>
  <wsdl:message name="processResponse">
    <wsdl:part name="processReturn" element="processReturn"/>
  </wsdl:message>
  <wsdl:message name="processRequest">
    <wsdl:part name="part" element="impl:process"/>
  </wsdl:message>
  <wsdl:portType name="MessagingService">
    <wsdl:operation name="process">
      <wsdl:input name="processRequest" message="impl:processRequest"/>
      <wsdl:output name="processResponse" message="impl:processResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="WSDLMessagingServiceSoapBinding" type="impl:MessagingService">
    <wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="process">
      <wsdlsoap:operation soapAction=""/>
      <wsdl:input name="processRequest">
        <wsdlsoap:body use="literal" namespace="http://www.astrogrid.org/registry"/>
      </wsdl:input>
      <wsdl:output name="processResponse">
        <wsdlsoap:body use="literal" namespace="http://www.astrogrid.org/registry"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="MessagingServiceService">
    <wsdl:port name="WSDLMessagingService" binding="impl:WSDLMessagingServiceSoapBinding">
      <wsdlsoap:address location="http://localhost:8080/astromessaging/services/WSDLMessagingService"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>