SELECT * FROM INSERT_NAME_CATALOG.INSERT_NAME_TABLE AS a WHERE 
   (
      (a."INSERT_NAME_DEC" <= INSERT_VALUE_MAX_DEC_RAD)  AND  
      (a."INSERT_NAME_DEC" >= INSERT_VALUE_MIN_DEC_RAD)
   ) 
   INSERT_RA_CLIP_CONDITION
   AND  
   ( 
      ACOS( 
         ( SIN(DEGREES(a."INSERT_NAME_DEC")) * SIN(INSERT_VALUE_DEC_DEG) )  +  
         ( COS(DEGREES(a."INSERT_NAME_DEC")) * COS(INSERT_VALUE_DEC_DEG) * 
                 COS( DEGREES(a."INSERT_NAME_RA") - INSERT_VALUE_RA_DEG) )
      ) <= INSERT_VALUE_CIRCRADIUS_DEG
   );
