/*
 * $Id: WarehouseServiceIfc.java,v 1.4 2003/11/07 14:50:01 gtr Exp $
 *
 * (C) Copyright AstroGrid...
 */

package org.astrogrid.warehouse.service;

import java.io.IOException;
import java.rmi.Remote;
import java.rmi.RemoteException;
import org.w3c.dom.Element;

/**
 * At the moment, basically a clone of the WarehouseDelegate interface.
 * Can add service-specific functionality in here later.
 *
 * @author K Andrews 
 */
public interface WarehouseServiceIfc extends Remote {

/**
  * Returns the metadata file
  * @soap
  */
  public Element getMetadata() throws java.rmi.RemoteException;

   /**
    * Returns metadata in a format suitable for a VO Registry
    * @soap
    */
  public Element getVoRegistryMetadata() throws java.rmi.RemoteException;

 /**
  * Returns VOTable
  */
  /*
  public Element coneSearch(double ra, double dec, double radius) 
                            throws java.rmi.RemoteException;
 */

 /**
 * takes an adql document and returns an id for the query.
 */
  public String makeQuery(Element adql, String resultsFormat) 
                          throws java.rmi.RemoteException;

 /**
  * set the myspace server where the results should be stored, for the 
  * given query id.
  */
  public void setResultsDestination(String id, String myspaceUrl) 
                                    throws java.rmi.RemoteException; 

 /** 
  * starts given query running
  */
  public void startQuery(String id) throws java.rmi.RemoteException;

 /**
  * - stops the given query
  */
  public void abortQuery(String id) throws java.rmi.RemoteException;

 /**
  * - gets info on the query status
  */
  public Element getStatus(String id) throws java.rmi.RemoteException;
}
/*
$Log: WarehouseServiceIfc.java,v $
Revision 1.4  2003/11/07 14:50:01  gtr
The interface now extends java.rmi.Remote. This is for compatibility with
the stubs generated by Axis.

Revision 1.3  2003/10/08 15:25:35  kea
Finalised interface classes required for end IT4 wk 2:
    org.astrogrid.warehouse.delegate.WarehouseDelegateIfc
    org.astrogrid.warehouse.service.WarehouseServiceIfc

Changed URL parameter to String parameter in setResultsDestination()
  methods to help with wsdl2java/java2wsdl auto-tooling.

Added package-specific WarehouseException.

Added wsdd files for deploying to Tomcat/Axis, and added temporary
testing harness just to be sure we can deploy to Axis and talk to the
(mostly unimplemented!) web service.

Revision 1.2  2003/10/07 17:09:51  kea
Adding webservice / webdelegate skeletons.
Having diffs with wsdl2java-generated class names/structure.

Revision 1.1  2003/10/06 15:47:49  kea
Initial check-in of interface skeletons, maven setup etc.

*/
