/* Generated by Together */

package org.astrogrid.mySpace.mySpaceServer;

//astrogrid
import org.astrogrid.mySpace.mySpaceRegistry.DataItemRecord;
import org.astrogrid.mySpace.mySpaceRegistry.MySpaceManager;
import org.astrogrid.mySpace.mySpaceRegistry.UserAccount;
//java
import java.util.Vector;
import java.io.PrintWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.lang.Exception;
import org.apache.log4j.Logger;

/**
 * @WebService
 * 
 * @author C L Qin
 * @version Iteration 2.
 */
public class ServerManager {
	
    private static Logger logger = Logger.getLogger(ServerManager.class);

    public String processRequest(){

    	return "";
    }

    /** userAcc = String usrID + String communityID
     * */
    public boolean deleteDataHolder(String dataHolderPath) {


      return true;
}

    public boolean exportDataHolder(String dataHolderPath, String destinationDataHolderPath) {

        return true;
    }

    public boolean copyDataHolder(String dataHolderPath, String destinationDataHolderPath) {

        return true;
    }

    public boolean moveDataHolder(String dataHolderPath, String destinationDataHolderPath) {

        return true;
    }

    public boolean saveDataHolder(String content, String dataHolderPath) 
	        throws Exception{
		PrintWriter printWriter = null;
		try{

			//logger.debug("YYY cotent = TEST saveDataHolder........");			
			
			File dataholder = new File(dataHolderPath);
			//open file to write into
			printWriter = new PrintWriter(new FileOutputStream(dataholder));    	    
    	    
			//write to file
			printWriter.println(content);
		    logger.debug("YYY content = "+content +"YYY path = " +dataHolderPath +" FilePath =" +dataholder.getAbsolutePath());
			return true;		    
				    
		}catch (Exception e) {//catch unexpected Exception
			//throw e;
			logger.error("YYY FAULT!!! "+e);
		}finally{
			//close file
			try{
				if(printWriter != null) {
					printWriter.close();
				}
			}catch(Exception e){
				throw e;
			}
			return false;
		}

        //return true;
    }

    //need to be decided not implement in Iteration 2
    public boolean tidyMySpace() {
    	return true;
    }

    /** given a size, return true or false indecate whether this action is doable
     *
     * */
    public int enquireDataHolderSize(UserAccount userAcc, int size) {
         
         return 0;
    }



    /**
     * @link aggregationByValue
     * @clientCardinality 1
     * @supplierCardinality 0..*
     */
    private DataHolder lnkDataRecord;
}
