//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.07.07 at 11:53:07 AM BST 
//


package org.astrogrid.applications.description.impl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *             Extra description necessary for describing the case where
 *             CEA acts as proxy to underlying service
 *          
 * 
 * <p>Java class for ProxyApplicationSetup complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProxyApplicationSetup">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="URL" type="{http://www.astrogrid.org/schema/CEAImplementation/v2.1}HttpURLType"/>
 *           &lt;element name="ResourceReferenceQuery" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProxyApplicationSetup", propOrder = {
    "url",
    "resourceReferenceQuery"
})
public class ProxyApplicationSetup {

    @XmlElement(name = "URL")
    protected HttpURLType url;
    @XmlElement(name = "ResourceReferenceQuery")
    protected String resourceReferenceQuery;

    /**
     * Gets the value of the url property.
     * 
     * @return
     *     possible object is
     *     {@link HttpURLType }
     *     
     */
    public HttpURLType getURL() {
        return url;
    }

    /**
     * Sets the value of the url property.
     * 
     * @param value
     *     allowed object is
     *     {@link HttpURLType }
     *     
     */
    public void setURL(HttpURLType value) {
        this.url = value;
    }

    /**
     * Gets the value of the resourceReferenceQuery property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResourceReferenceQuery() {
        return resourceReferenceQuery;
    }

    /**
     * Sets the value of the resourceReferenceQuery property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResourceReferenceQuery(String value) {
        this.resourceReferenceQuery = value;
    }

}
