package org.astrogrid.jes.delegate.jobController;

import junit.framework.TestCase;
// JUnitDoclet begin import
import org.astrogrid.jes.delegate.jobController.JobControllerServiceLocator;
// JUnitDoclet end import

/**
* Generated by JUnitDoclet, a tool provided by
* ObjectFab GmbH under LGPL.
* Please see www.junitdoclet.org, www.gnu.org
* and www.objectfab.de for informations about
* the tool, the licence and the authors.
* @TODO This test was autogenerated - needs fleshing out
* */


public class JobControllerServiceLocatorTest
// JUnitDoclet begin extends_implements
extends TestCase
// JUnitDoclet end extends_implements
{
  // JUnitDoclet begin class
  org.astrogrid.jes.delegate.jobController.JobControllerServiceLocator jobcontrollerservicelocator = null;
  // JUnitDoclet end class
  
  public JobControllerServiceLocatorTest(String name) {
    // JUnitDoclet begin method JobControllerServiceLocatorTest
    super(name);
    // JUnitDoclet end method JobControllerServiceLocatorTest
  }
  
  public org.astrogrid.jes.delegate.jobController.JobControllerServiceLocator createInstance() throws Exception {
    // JUnitDoclet begin method testcase.createInstance
    return new org.astrogrid.jes.delegate.jobController.JobControllerServiceLocator();
    // JUnitDoclet end method testcase.createInstance
  }
  
  protected void setUp() throws Exception {
    // JUnitDoclet begin method testcase.setUp
    super.setUp();
    jobcontrollerservicelocator = createInstance();
    // JUnitDoclet end method testcase.setUp
  }
  
  protected void tearDown() throws Exception {
    // JUnitDoclet begin method testcase.tearDown
    jobcontrollerservicelocator = null;
    super.tearDown();
    // JUnitDoclet end method testcase.tearDown
  }
  
  public void testGetJobControllerServiceAddress() throws Exception {
    // JUnitDoclet begin method getJobControllerServiceAddress
    // JUnitDoclet end method getJobControllerServiceAddress
  }
  
  public void testSetGetJobControllerServiceWSDDServiceName() throws Exception {
    // JUnitDoclet begin method setJobControllerServiceWSDDServiceName getJobControllerServiceWSDDServiceName
    java.lang.String[] tests = {"", " ", "a", "A", "�", "�", "0123456789", "012345678901234567890", "\n", null};
    
    for (int i = 0; i < tests.length; i++) {
      jobcontrollerservicelocator.setJobControllerServiceWSDDServiceName(tests[i]);
      assertEquals(tests[i], jobcontrollerservicelocator.getJobControllerServiceWSDDServiceName());
    }
    // JUnitDoclet end method setJobControllerServiceWSDDServiceName getJobControllerServiceWSDDServiceName
  }
  
  public void testGetJobControllerService() throws Exception {
    // JUnitDoclet begin method getJobControllerService
    // JUnitDoclet end method getJobControllerService
  }
  
  public void testGetPort() throws Exception {
    // JUnitDoclet begin method getPort
    // JUnitDoclet end method getPort
  }
  
  public void testGetServiceName() throws Exception {
    // JUnitDoclet begin method getServiceName
    // JUnitDoclet end method getServiceName
  }
  
  public void testGetPorts() throws Exception {
    // JUnitDoclet begin method getPorts
    // JUnitDoclet end method getPorts
  }
  
  
  
  /**
  * JUnitDoclet moves marker to this method, if there is not match
  * for them in the regenerated code and if the marker is not empty.
  * This way, no test gets lost when regenerating after renaming.
  * Method testVault is supposed to be empty.
  */
  public void testVault() throws Exception {
    // JUnitDoclet begin method testcase.testVault
    // JUnitDoclet end method testcase.testVault
  }
  
  public static void main(String[] args) {
    // JUnitDoclet begin method testcase.main
    junit.textui.TestRunner.run(JobControllerServiceLocatorTest.class);
    // JUnitDoclet end method testcase.main
  }
}
