/*
 * $Id: AdqlQuerier.java,v 1.5 2004/03/08 15:54:57 mch Exp $
 *
 * (C) Copyright AstroGrid...
 */

package org.astrogrid.datacenter.delegate;

import java.io.IOException;
import org.astrogrid.datacenter.adql.generated.Select;
import org.w3c.dom.Document;

/**
 * Defines the interface for clients that want to submit ADQL queries
 *
 * @author M Hill
 * @deprecated this interface is obsolete - use {@link FullSearcher} instead. Expect this interface to
 * dissapear very soon.
 */

public interface AdqlQuerier
{
   public final static String VOTABLE = FullSearcher.VOTABLE;
   
   /**
    * Simple blocking query.
    * @param user user information for authentication/authorisation
    * @param resultsformat string specifying how the results will be returned (eg
    * votable, fits, etc) strings as given in the datacenter's metadata
    * @param ADQL
    */
   public DatacenterResults doQuery(String resultsFormat,  Select adql) throws IOException;

   /**
    * Returns the number of items that match the given query.  This is useful for
    * doing checks on how big the result set is likely to be before it has to be
    * transferred about the net.
    */
   public int countQuery(Select adql) throws IOException;


   /**
    * Constructs the query at the
    * server end, but does not start it yet as other Things May Need To Be Done
    * such as registering listeners or setting the destination for the results.
    *
    * @param adql object model
    */
   public DatacenterQuery makeQuery(Select adql) throws IOException;

   /**
    * Constructs the query at the
    * server end, but does not start it yet as other Things May Need To Be Done
    * such as registering listeners or setting the destination for the results.
    *
    * @param adql object model
    * @param givenId an id for the query is assigned here rather than
    * generated by the server
    */
   public DatacenterQuery makeQuery(Select adql, String givenId) throws IOException;


    /**
     * returns the full datacenter metadata.  Implementations might like to
     * cache it locally (but remember threadsafety)...
     */
   public Document getMetadata() throws IOException;

}

/*
$Log: AdqlQuerier.java,v $
Revision 1.5  2004/03/08 15:54:57  mch
Better exception passing, removed Metdata

Revision 1.4  2004/01/13 00:32:47  nw
Merged in branch providing
* sql pass-through
* replace Certification by User
* Rename _query as Query

Revision 1.3.10.2  2004/01/12 16:44:07  nw
Reintroduced deprecated interfaces for backwards compatability

sql passthru finished and tested

Revision 1.3  2003/11/26 16:31:46  nw
altered transport to accept any query format.
moved back to axis from castor

Revision 1.2  2003/11/25 11:54:41  mch
Added framework for SQL-passthrough queries

Revision 1.1  2003/11/14 00:36:40  mch
Code restructure

Revision 1.2  2003/11/05 18:52:53  mch
Build fixes for change to SOAPy Beans and new delegates

Revision 1.1  2003/10/06 18:55:21  mch
Naughtily large set of changes converting to SOAPy bean/interface-based delegates

*/


