/*
 * $Id: FullSearcher.java,v 1.3 2004/01/14 13:12:47 nw Exp $
 *
 * (C) Copyright AstroGrid...
 */

package org.astrogrid.datacenter.delegate;

import java.io.IOException;

import org.w3c.dom.Element;

/**
 * Defines the interface for clients that want to query using complex query languages
 *
 * @author nww
 * @see org.astrogrid.datacenter.adql.ADQLUtils
 * @see org.astrogrid.datacenter.sql.SQLUtils
 */

public interface FullSearcher
{
   public final static String VOTABLE = "Votable"; //results format
   
   /**
    * Simple blocking query.
    * @param user user information for authentication/authorisation
    * @param resultsformat string specifying how the results will be returned (eg
    * votable, fits, etc) strings as given in the datacenter's metadata
    * @param queryBody query language statement as xml element
    * @see org.astrogrid.datacenter.adql.ADQLUtils#toQueryBody
    * @see org.astrogrid.datacentrer.sql.SQLUtils#toQueryBody
    */
   public DatacenterResults doQuery(String resultsFormat,  Element queryBody) throws IOException;

   /**
    * Returns the number of items that match the given query.  This is useful for
    * doing checks on how big the result set is likely to be before it has to be
    * transferred about the net.
    *     * @see org.astrogrid.datacenter.adql.ADQLUtils#toQueryBody
    * @see org.astrogrid.datacentrer.sql.SQLUtils#toQueryBody
    */
   public int countQuery(Element queryBody) throws IOException;


   /**
    * Constructs the query at the
    * server end, but does not start it yet as other Things May Need To Be Done
    * such as registering listeners or setting the destination for the results.
    *
    * @param queryBody query language statement
        * @see org.astrogrid.datacenter.adql.ADQLUtils#toQueryBody
    * @see org.astrogrid.datacentrer.sql.SQLUtils#toQueryBody 
    */
   public DatacenterQuery makeQuery(Element queryBody) throws IOException;

   /**
    * Constructs the query at the
    * server end, but does not start it yet as other Things May Need To Be Done
    * such as registering listeners or setting the destination for the results.
    *
    * @param queryBody query language statement
    * @param givenId an id for the query is assigned here rather than
    * generated by the server
    *     * @see org.astrogrid.datacenter.adql.ADQLUtils#toQueryBody
    * @see org.astrogrid.datacentrer.sql.SQLUtils#toQueryBody
    */
   public DatacenterQuery makeQuery(Element queryBody, String givenId) throws IOException;


    /**
     * returns the full datacenter metadata.  Implementations might like to
     * cache it locally (but remember threadsafety)...
     */
   public Metadata getMetadata() throws IOException;

}

/*
$Log: FullSearcher.java,v $
Revision 1.3  2004/01/14 13:12:47  nw
improved documentation

Revision 1.2  2004/01/13 00:32:47  nw
Merged in branch providing
* sql pass-through
* replace Certification by User
* Rename _query as Query

Revision 1.1.2.1  2004/01/07 15:25:44  nw
removed adql-specific nature.

Revision 1.3  2003/11/26 16:31:46  nw
altered transport to accept any query format.
moved back to axis from castor

Revision 1.2  2003/11/25 11:54:41  mch
Added framework for SQL-passthrough queries

Revision 1.1  2003/11/14 00:36:40  mch
Code restructure

Revision 1.2  2003/11/05 18:52:53  mch
Build fixes for change to SOAPy Beans and new delegates

Revision 1.1  2003/10/06 18:55:21  mch
Naughtily large set of changes converting to SOAPy bean/interface-based delegates

*/


