/*
 * $Id: ExecutionPhase.java,v 1.3 2011/09/13 13:43:29 pah Exp $
 * Copyright 2011 Paul Harrison (paul.harrison@manchester.ac.uk)
 *
 * File originally generated by JAXB, but since hand updated
 */


package net.ivoa.uws;

import javax.xml.bind.annotation.XmlEnum;


/**
 * <p>Java class for ExecutionPhase.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ExecutionPhase">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="PENDING"/>
 *     &lt;enumeration value="QUEUED"/>
 *     &lt;enumeration value="EXECUTING"/>
 *     &lt;enumeration value="COMPLETED"/>
 *     &lt;enumeration value="ERROR"/>
 *     &lt;enumeration value="UNKNOWN"/>
 *     &lt;enumeration value="HELD"/>
 *     &lt;enumeration value="SUSPENDED"/>
 *     &lt;enumeration value="ABORTED"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum ExecutionPhase {

    PENDING,
    QUEUED,
    EXECUTING,
    COMPLETED,
    ERROR,
    UNKNOWN,
    HELD,
    SUSPENDED,
    ABORTED;

    public String value() {
        return name();
    }

    public static ExecutionPhase fromValue(String v) {
        return valueOf(v);
    }

}
