//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.07.14 at 10:25:34 PM BST 
//


package org.astrogrid.applications.description.execution;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import net.ivoa.uws.JobSummary;


/**
 * <p>Java class for execution-summary-type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="execution-summary-type">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ivoa.net/xml/UWS/v1.0rc3}JobSummary">
 *       &lt;sequence>
 *         &lt;element name="application-name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="inputList" type="{http://www.ivoa.net/xml/CEA/types/v1.2}InputList"/>
 *         &lt;element name="outputList" type="{http://www.ivoa.net/xml/CEA/types/v1.2}ResultListType"/>
 *         &lt;element name="log" type="{http://www.ivoa.net/xml/CEA/types/v1.2}message-type" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "execution-summary-type", propOrder = {
    "applicationName",
    "inputList",
    "outputList",
    "log"
})
public class ExecutionSummaryType
    extends JobSummary
{

    @XmlElement(name = "application-name", required = true)
    protected String applicationName;
    @XmlElement(required = true)
    protected InputList inputList;
    @XmlElement(required = true)
    protected ResultListType outputList;
    @XmlElement(type = MessageType.class)
    protected List<MessageType> log;

    /**
     * Gets the value of the applicationName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicationName() {
        return applicationName;
    }

    /**
     * Sets the value of the applicationName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicationName(String value) {
        this.applicationName = value;
    }

    /**
     * Gets the value of the inputList property.
     * 
     * @return
     *     possible object is
     *     {@link InputList }
     *     
     */
    public InputList getInputList() {
        return inputList;
    }

    /**
     * Sets the value of the inputList property.
     * 
     * @param value
     *     allowed object is
     *     {@link InputList }
     *     
     */
    public void setInputList(InputList value) {
        this.inputList = value;
    }

    /**
     * Gets the value of the outputList property.
     * 
     * @return
     *     possible object is
     *     {@link ResultListType }
     *     
     */
    public ResultListType getOutputList() {
        return outputList;
    }

    /**
     * Sets the value of the outputList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResultListType }
     *     
     */
    public void setOutputList(ResultListType value) {
        this.outputList = value;
    }

    /**
     * Gets the value of the log property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the log property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLog().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MessageType }
     * 
     * 
     */
    public List<MessageType> getLog() {
        if (log == null) {
            log = new ArrayList<MessageType>();
        }
        return this.log;
    }

}
