/* Generated By: AdqlStoX.jjt,v 1.36.2.4 2008/02/01 09&JJTree&JavaCC: Do not edit this line. AdqlStoXConstants.java */
package org.astrogrid.adql ;

public interface AdqlStoXConstants {

  int EOF = 0;
  int COMMENT = 1;
  int SINGLE_LINE_COMMENT = 2;
  int DOUBLE_QUOTE = 7;
  int PERCENT = 8;
  int AMPERSAND = 9;
  int QUOTE = 10;
  int LEFT_PAREN = 11;
  int RIGHT_PAREN = 12;
  int ASTERISK = 13;
  int PLUS_SIGN = 14;
  int COMMA = 15;
  int MINUS_SIGN = 16;
  int PERIOD = 17;
  int SOLIDUS = 18;
  int COLON = 19;
  int SEMICOLON = 20;
  int LESS_THAN_OPERATOR = 21;
  int EQUALS_OPERATOR = 22;
  int GREATER_THEN_OPERATOR = 23;
  int QUESTION_MARK = 24;
  int UNDERSCORE = 25;
  int VERTICAL_BAR = 26;
  int LEFT_BRACKET = 27;
  int RIGHT_BRACKET = 28;
  int ABSOLUTE = 29;
  int ACTION = 30;
  int ADD = 31;
  int ALL = 32;
  int ALLOCATE = 33;
  int ALTER = 34;
  int AND = 35;
  int ANY = 36;
  int ARE = 37;
  int AS = 38;
  int ASC = 39;
  int ASSERTION = 40;
  int AT = 41;
  int AUTHORIZATION = 42;
  int AVG = 43;
  int BEGIN = 44;
  int BETWEEN = 45;
  int BIT = 46;
  int BIT_LENGTH = 47;
  int BOTH = 48;
  int BY = 49;
  int CASCADE = 50;
  int CASCADED = 51;
  int CASE = 52;
  int CAST = 53;
  int CATALOG = 54;
  int CHAR = 55;
  int CHARACTER = 56;
  int CHAR_LENGTH = 57;
  int CHARACTER_LENGTH = 58;
  int CHECK = 59;
  int CLOSE = 60;
  int COALESCE = 61;
  int COLLATE = 62;
  int COLLATION = 63;
  int COLUMN = 64;
  int COMMIT = 65;
  int CONNECT = 66;
  int CONNECTION = 67;
  int CONSTRAINT = 68;
  int CONSTRAINTS = 69;
  int CONTINUE = 70;
  int CONVERT = 71;
  int CORRESPONDING = 72;
  int COUNT = 73;
  int CREATE = 74;
  int CROSS = 75;
  int CURRENT = 76;
  int CURRENT_DATE = 77;
  int CURRENT_TIME = 78;
  int CURRENT_TIMESTAMP = 79;
  int CURRENT_USER = 80;
  int CURSOR = 81;
  int DATE = 82;
  int DAY = 83;
  int DEALLOCATE = 84;
  int DECIMAL = 85;
  int DECLARE = 86;
  int SQL_DEFAULT = 87;
  int DEFERRABLE = 88;
  int DEFERRED = 89;
  int DELETE = 90;
  int DESC = 91;
  int DESCRIBE = 92;
  int DESCRIPTOR = 93;
  int DIAGNOSTICS = 94;
  int DISCONNECT = 95;
  int DISTINCT = 96;
  int DOMAIN = 97;
  int DOUBLE = 98;
  int DROP = 99;
  int ELSE = 100;
  int END = 101;
  int ENDEXEC = 102;
  int ESCAPE = 103;
  int EXCEPT = 104;
  int EXCEPTION = 105;
  int EXEC = 106;
  int EXECUTE = 107;
  int EXISTS = 108;
  int EXTERNAL = 109;
  int EXTRACT = 110;
  int FALSE = 111;
  int FETCH = 112;
  int FIRST = 113;
  int FLOAT = 114;
  int FOR = 115;
  int FOREIGN = 116;
  int FOUND = 117;
  int FROM = 118;
  int FULL = 119;
  int GET = 120;
  int GLOBAL = 121;
  int GO = 122;
  int GOTO = 123;
  int GRANT = 124;
  int GROUP = 125;
  int HAVING = 126;
  int HOUR = 127;
  int IDENTITY = 128;
  int IMMEDIATE = 129;
  int IN = 130;
  int INDICATOR = 131;
  int INITIALLY = 132;
  int INNER = 133;
  int INPUT = 134;
  int INSENSITIVE = 135;
  int INSERT = 136;
  int INT = 137;
  int INTEGER = 138;
  int INTERSECT = 139;
  int INTERVAL = 140;
  int INTO = 141;
  int IS = 142;
  int ISOLATION = 143;
  int JOIN = 144;
  int KEY = 145;
  int LANGUAGE = 146;
  int LAST = 147;
  int LEADING = 148;
  int LEFT = 149;
  int LEVEL = 150;
  int LIKE = 151;
  int LOCAL = 152;
  int LOWER = 153;
  int MATCH = 154;
  int MAX = 155;
  int MIN = 156;
  int MINUTE = 157;
  int MODULE = 158;
  int MONTH = 159;
  int NAMES = 160;
  int NATIONAL = 161;
  int NATURAL = 162;
  int NCHAR = 163;
  int NEXT = 164;
  int NO = 165;
  int NOT = 166;
  int NULL = 167;
  int NULLIF = 168;
  int NUMERIC = 169;
  int OCTET_LENGTH = 170;
  int OF = 171;
  int ON = 172;
  int ONLY = 173;
  int OPEN = 174;
  int OPTION = 175;
  int OR = 176;
  int ORDER = 177;
  int OUTER = 178;
  int OUTPUT = 179;
  int OVERLAPS = 180;
  int PAD = 181;
  int PARTIAL = 182;
  int POSITION = 183;
  int PRECISION = 184;
  int PREPARE = 185;
  int PRESERVE = 186;
  int PRIMARY = 187;
  int PRIOR = 188;
  int PRIVILEGES = 189;
  int PROCEDURE = 190;
  int PUBLIC = 191;
  int READ = 192;
  int REAL = 193;
  int REFERENCES = 194;
  int RELATIVE = 195;
  int RESTRICT = 196;
  int REVOKE = 197;
  int RIGHT = 198;
  int ROLLBACK = 199;
  int ROWS = 200;
  int SCHEMA = 201;
  int SCROLL = 202;
  int SECOND = 203;
  int SECTION = 204;
  int SELECT = 205;
  int SESSION = 206;
  int SESSION_USER = 207;
  int SET = 208;
  int SIZE = 209;
  int SMALLINT = 210;
  int SOME = 211;
  int SPACE = 212;
  int SQL = 213;
  int SQLCODE = 214;
  int SQLERROR = 215;
  int SQLSTATE = 216;
  int SUBSTRING = 217;
  int SUM = 218;
  int SYSTEM_USER = 219;
  int TABLE = 220;
  int TEMPORARY = 221;
  int THEN = 222;
  int TIME = 223;
  int TIMESTAMP = 224;
  int TIMEZONE_HOUR = 225;
  int TIMEZONE_MINUTE = 226;
  int TO = 227;
  int TRAILING = 228;
  int TRANSACTION = 229;
  int TRANSLATE = 230;
  int TRANSLATION = 231;
  int TRIM = 232;
  int TRUE = 233;
  int UNION = 234;
  int UNIQUE = 235;
  int UNKNOWN = 236;
  int UPDATE = 237;
  int UPPER = 238;
  int USAGE = 239;
  int USER = 240;
  int USING = 241;
  int VALUE = 242;
  int VALUES = 243;
  int VARCHAR = 244;
  int VARYING = 245;
  int VIEW = 246;
  int WHEN = 247;
  int WHENEVER = 248;
  int WHERE = 249;
  int WITH = 250;
  int WORK = 251;
  int WRITE = 252;
  int YEAR = 253;
  int ZONE = 254;
  int TOP = 255;
  int XMATCH = 256;
  int REGION = 257;
  int CIRCLE = 258;
  int ELLIPSE = 259;
  int POLYGON = 260;
  int SECTOR = 261;
  int CONVEX = 262;
  int CONVEX_HULL = 263;
  int INTERSECTION = 264;
  int FILL_FACTOR = 265;
  int UNIT = 266;
  int COORD_SYSTEM = 267;
  int CENTER = 268;
  int RADIUS = 269;
  int RADII = 270;
  int POS_ANGLE = 271;
  int DEG = 272;
  int DEG_DEG_M = 273;
  int RAD = 274;
  int H = 275;
  int ARCMIN = 276;
  int ARCSEC = 277;
  int M = 278;
  int KM = 279;
  int MM = 280;
  int AU = 281;
  int PC = 282;
  int KPC = 283;
  int MPC = 284;
  int LYR = 285;
  int ABS = 286;
  int CEILING = 287;
  int DEGREES = 288;
  int EXP = 289;
  int FLOOR = 290;
  int LOG = 291;
  int PI = 292;
  int POWER = 293;
  int RADIANS = 294;
  int SQRT = 295;
  int SQUARE = 296;
  int LOG10 = 297;
  int RAND = 298;
  int ROUND = 299;
  int TRUNCATE = 300;
  int SIN = 301;
  int COS = 302;
  int TAN = 303;
  int COT = 304;
  int ASIN = 305;
  int ACOS = 306;
  int ATAN = 307;
  int ATAN2 = 308;
  int ASCII_STRING_LITERAL = 309;
  int LBRACE = 310;
  int RBRACE = 311;
  int DOLLAR = 312;
  int NOT_EQUALS_OPERATOR = 313;
  int LESS_THAN_OR_EQUALS_OPERATOR = 314;
  int GREATER_THAN_OR_EQUALS_OPERATOR = 315;
  int CROSS_JOIN = 316;
  int GROUPBY = 317;
  int ORDERBY = 318;
  int TIME_ZONE = 319;
  int TRUTH_VALUE = 320;
  int REGULAR_IDENTIFIER = 321;
  int DELIMITED_IDENTIFIER = 322;
  int LETTER = 323;
  int SPECIAL_CHARS = 324;
  int UNSIGNED_INTEGER = 325;
  int DIGIT = 326;
  int APPROXIMATE_NUMERIC_LITERAL = 327;
  int EXACT_NUMERIC_LITERAL = 328;
  int MANTISSA = 329;
  int EXPONENT = 330;
  int SIGNED_INTEGER = 331;
  int E = 332;
  int SIGN = 333;
  int OTHER = 334;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<COMMENT>",
    "<SINGLE_LINE_COMMENT>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\\"\\\"\"",
    "\"%\"",
    "\"&\"",
    "\"\\\'\"",
    "\"(\"",
    "\")\"",
    "\"*\"",
    "\"+\"",
    "\",\"",
    "\"-\"",
    "\".\"",
    "\"/\"",
    "\":\"",
    "\";\"",
    "\"<\"",
    "\"=\"",
    "\">\"",
    "\"?\"",
    "\"_\"",
    "\"|\"",
    "\"[\"",
    "\"]\"",
    "\"absolute\"",
    "\"action\"",
    "\"add\"",
    "\"all\"",
    "\"allocate\"",
    "\"alter\"",
    "\"and\"",
    "\"any\"",
    "\"are\"",
    "\"as\"",
    "\"asc\"",
    "\"assertion\"",
    "\"at\"",
    "\"authorization\"",
    "\"avg\"",
    "\"begin\"",
    "\"between\"",
    "\"bit\"",
    "\"bit_length\"",
    "\"both\"",
    "\"by\"",
    "\"cascade\"",
    "\"cascaded\"",
    "\"case\"",
    "\"cast\"",
    "\"catalog\"",
    "\"char\"",
    "\"character\"",
    "\"char_length\"",
    "\"character_length\"",
    "\"check\"",
    "\"close\"",
    "\"coalesce\"",
    "\"collate\"",
    "\"collation\"",
    "\"column\"",
    "\"commit\"",
    "\"connect\"",
    "\"connection\"",
    "\"constraint\"",
    "\"constraints\"",
    "\"continue\"",
    "\"convert\"",
    "\"corresponding\"",
    "\"count\"",
    "\"create\"",
    "\"cross\"",
    "\"current\"",
    "\"current_date\"",
    "\"current_time\"",
    "\"current_timestamp\"",
    "\"current_user\"",
    "\"cursor\"",
    "\"date\"",
    "\"day\"",
    "\"deallocate\"",
    "\"decimal\"",
    "\"declare\"",
    "\"default\"",
    "\"deferrable\"",
    "\"deferred\"",
    "\"delete\"",
    "\"desc\"",
    "\"describe\"",
    "\"descriptor\"",
    "\"diagnostics\"",
    "\"disconnect\"",
    "\"distinct\"",
    "\"domain\"",
    "\"double\"",
    "\"drop\"",
    "\"else\"",
    "\"end\"",
    "\"end-exec\"",
    "\"escape\"",
    "\"except\"",
    "\"exception\"",
    "\"exec\"",
    "\"execute\"",
    "\"exists\"",
    "\"external\"",
    "\"extract\"",
    "\"false\"",
    "\"fetch\"",
    "\"first\"",
    "\"float\"",
    "\"for\"",
    "\"foreign\"",
    "\"found\"",
    "\"from\"",
    "\"full\"",
    "\"get\"",
    "\"global\"",
    "\"go\"",
    "\"goto\"",
    "\"grant\"",
    "\"group\"",
    "\"having\"",
    "\"hour\"",
    "\"identity\"",
    "\"immediate\"",
    "\"in\"",
    "\"indicator\"",
    "\"initially\"",
    "\"inner\"",
    "\"input\"",
    "\"insensitive\"",
    "\"insert\"",
    "\"int\"",
    "\"integer\"",
    "\"instersect\"",
    "\"interval\"",
    "\"into\"",
    "\"is\"",
    "\"isolation\"",
    "\"join\"",
    "\"key\"",
    "\"language\"",
    "\"last\"",
    "\"leading\"",
    "\"left\"",
    "\"level\"",
    "\"like\"",
    "\"local\"",
    "\"lower\"",
    "\"match\"",
    "\"max\"",
    "\"min\"",
    "\"minute\"",
    "\"module\"",
    "\"month\"",
    "\"names\"",
    "\"national\"",
    "\"natural\"",
    "\"nchar\"",
    "\"next\"",
    "\"no\"",
    "\"not\"",
    "\"null\"",
    "\"nullif\"",
    "\"numeric\"",
    "\"octet_length\"",
    "\"of\"",
    "\"on\"",
    "\"only\"",
    "\"open\"",
    "\"option\"",
    "\"or\"",
    "\"order\"",
    "\"outer\"",
    "\"output\"",
    "\"overlaps\"",
    "\"pad\"",
    "\"partial\"",
    "\"position\"",
    "\"precision\"",
    "\"prepare\"",
    "\"preserve\"",
    "\"primary\"",
    "\"prior\"",
    "\"privileges\"",
    "\"procedure\"",
    "\"public\"",
    "\"read\"",
    "\"real\"",
    "\"references\"",
    "\"relative\"",
    "\"restrict\"",
    "\"revoke\"",
    "\"right\"",
    "\"rollback\"",
    "\"rows\"",
    "\"schema\"",
    "\"scroll\"",
    "\"second\"",
    "\"section\"",
    "\"select\"",
    "\"session\"",
    "\"session_user\"",
    "\"set\"",
    "\"size\"",
    "\"smallint\"",
    "\"some\"",
    "\"space\"",
    "\"sql\"",
    "\"sqlcode\"",
    "\"sqlerror\"",
    "\"sqlstate\"",
    "\"substring\"",
    "\"sum\"",
    "\"system_user\"",
    "\"table\"",
    "\"temporary\"",
    "\"then\"",
    "\"time\"",
    "\"timestamp\"",
    "\"timezone_hour\"",
    "\"timezone_minute\"",
    "\"to\"",
    "\"trailing\"",
    "\"transaction\"",
    "\"translate\"",
    "\"translation\"",
    "\"trim\"",
    "\"true\"",
    "\"union\"",
    "\"unique\"",
    "\"unknown\"",
    "\"update\"",
    "\"upper\"",
    "\"usage\"",
    "\"user\"",
    "\"using\"",
    "\"value\"",
    "\"values\"",
    "\"varchar\"",
    "\"varying\"",
    "\"view\"",
    "\"when\"",
    "\"whenever\"",
    "\"where\"",
    "\"with\"",
    "\"work\"",
    "\"write\"",
    "\"year\"",
    "\"zone\"",
    "\"top\"",
    "\"xmatch\"",
    "\"region\"",
    "\"circle\"",
    "\"ellipse\"",
    "\"polygon\"",
    "\"sector\"",
    "\"convex\"",
    "\"convex hull\"",
    "\"intersection\"",
    "\"fill factor\"",
    "\"unit\"",
    "<COORD_SYSTEM>",
    "\"center\"",
    "\"radius\"",
    "\"radii\"",
    "\"angle\"",
    "\"deg\"",
    "\"deg deg m\"",
    "\"rad\"",
    "\"_h_\"",
    "\"arcmin\"",
    "\"arcsec\"",
    "\"_m_\"",
    "\"km\"",
    "\"mm\"",
    "\"au\"",
    "\"pc\"",
    "\"kpc\"",
    "\"Mpc\"",
    "\"lyr\"",
    "\"abs\"",
    "\"ceiling\"",
    "\"degrees\"",
    "\"exp\"",
    "\"floor\"",
    "\"log\"",
    "\"pi\"",
    "\"power\"",
    "\"radians\"",
    "\"sqrt\"",
    "\"square\"",
    "\"log10\"",
    "\"rand\"",
    "\"round\"",
    "\"truncate\"",
    "\"sin\"",
    "\"cos\"",
    "\"tan\"",
    "\"cot\"",
    "\"asin\"",
    "\"acos\"",
    "\"atan\"",
    "\"atan2\"",
    "<ASCII_STRING_LITERAL>",
    "\"{\"",
    "\"}\"",
    "\"$\"",
    "<NOT_EQUALS_OPERATOR>",
    "\"<=\"",
    "\">=\"",
    "\"cross join\"",
    "\"group by\"",
    "\"order by\"",
    "\"TIME ZONE\"",
    "<TRUTH_VALUE>",
    "<REGULAR_IDENTIFIER>",
    "<DELIMITED_IDENTIFIER>",
    "<LETTER>",
    "<SPECIAL_CHARS>",
    "<UNSIGNED_INTEGER>",
    "<DIGIT>",
    "<APPROXIMATE_NUMERIC_LITERAL>",
    "<EXACT_NUMERIC_LITERAL>",
    "<MANTISSA>",
    "<EXPONENT>",
    "<SIGNED_INTEGER>",
    "<E>",
    "<SIGN>",
    "<OTHER>",
    "\"5-TBD caseExpression\"",
    "\"6-TBD castSpecification\"",
  };

}
