/* Generated By: AdqlStoX.jjt,v 1.34.2.35 2007/06/06 10&JJTree&JavaCC: Do not edit this line. AdqlStoXConstants.java */
package org.astrogrid.adql ;

public interface AdqlStoXConstants {

  int EOF = 0;
  int COMMENT = 1;
  int SINGLE_LINE_COMMENT = 2;
  int DOUBLE_QUOTE = 7;
  int PERCENT = 8;
  int AMPERSAND = 9;
  int QUOTE = 10;
  int LEFT_PAREN = 11;
  int RIGHT_PAREN = 12;
  int ASTERISK = 13;
  int PLUS_SIGN = 14;
  int COMMA = 15;
  int MINUS_SIGN = 16;
  int PERIOD = 17;
  int SOLIDUS = 18;
  int COLON = 19;
  int SEMICOLON = 20;
  int LESS_THAN_OPERATOR = 21;
  int EQUALS_OPERATOR = 22;
  int GREATER_THEN_OPERATOR = 23;
  int QUESTION_MARK = 24;
  int UNDERSCORE = 25;
  int VERTICAL_BAR = 26;
  int LEFT_BRACKET = 27;
  int RIGHT_BRACKET = 28;
  int ABSOLUTE = 29;
  int ACTION = 30;
  int ADD = 31;
  int ALL = 32;
  int ALLOCATE = 33;
  int ALTER = 34;
  int AND = 35;
  int ANY = 36;
  int ARE = 37;
  int AS = 38;
  int ASC = 39;
  int ASSERTION = 40;
  int AT = 41;
  int AUTHORIZATION = 42;
  int AVG = 43;
  int BEGIN = 44;
  int BETWEEN = 45;
  int BIT = 46;
  int BIT_LENGTH = 47;
  int BOTH = 48;
  int BY = 49;
  int CASCADE = 50;
  int CASCADED = 51;
  int CASE = 52;
  int CAST = 53;
  int CATALOG = 54;
  int CHAR = 55;
  int CHARACTER = 56;
  int CHAR_LENGTH = 57;
  int CHARACTER_LENGTH = 58;
  int CHECK = 59;
  int CLOSE = 60;
  int COALESCE = 61;
  int COLLATE = 62;
  int COLLATION = 63;
  int COLUMN = 64;
  int COMMIT = 65;
  int CONNECT = 66;
  int CONNECTION = 67;
  int CONSTRAINT = 68;
  int CONSTRAINTS = 69;
  int CONTINUE = 70;
  int CONVERT = 71;
  int CORRESPONDING = 72;
  int COUNT = 73;
  int CREATE = 74;
  int CROSS = 75;
  int CURRENT = 76;
  int CURRENT_DATE = 77;
  int CURRENT_TIME = 78;
  int CURRENT_TIMESTAMP = 79;
  int CURRENT_USER = 80;
  int CURSOR = 81;
  int DATE = 82;
  int DAY = 83;
  int DEALLOCATE = 84;
  int DEC = 85;
  int DECIMAL = 86;
  int DECLARE = 87;
  int SQL_DEFAULT = 88;
  int DEFERRABLE = 89;
  int DEFERRED = 90;
  int DELETE = 91;
  int DESC = 92;
  int DESCRIBE = 93;
  int DESCRIPTOR = 94;
  int DIAGNOSTICS = 95;
  int DISCONNECT = 96;
  int DISTINCT = 97;
  int DOMAIN = 98;
  int DOUBLE = 99;
  int DROP = 100;
  int ELSE = 101;
  int END = 102;
  int ENDEXEC = 103;
  int ESCAPE = 104;
  int EXCEPT = 105;
  int EXCEPTION = 106;
  int EXEC = 107;
  int EXECUTE = 108;
  int EXISTS = 109;
  int EXTERNAL = 110;
  int EXTRACT = 111;
  int FALSE = 112;
  int FETCH = 113;
  int FIRST = 114;
  int FLOAT = 115;
  int FOR = 116;
  int FOREIGN = 117;
  int FOUND = 118;
  int FROM = 119;
  int FULL = 120;
  int GET = 121;
  int GLOBAL = 122;
  int GO = 123;
  int GOTO = 124;
  int GRANT = 125;
  int GROUP = 126;
  int HAVING = 127;
  int HOUR = 128;
  int IDENTITY = 129;
  int IMMEDIATE = 130;
  int IN = 131;
  int INDICATOR = 132;
  int INITIALLY = 133;
  int INNER = 134;
  int INPUT = 135;
  int INSENSITIVE = 136;
  int INSERT = 137;
  int INT = 138;
  int INTEGER = 139;
  int INTERSECT = 140;
  int INTERVAL = 141;
  int INTO = 142;
  int IS = 143;
  int ISOLATION = 144;
  int JOIN = 145;
  int KEY = 146;
  int LANGUAGE = 147;
  int LAST = 148;
  int LEADING = 149;
  int LEFT = 150;
  int LEVEL = 151;
  int LIKE = 152;
  int LOCAL = 153;
  int LOWER = 154;
  int MATCH = 155;
  int MAX = 156;
  int MIN = 157;
  int MINUTE = 158;
  int MODULE = 159;
  int MONTH = 160;
  int NAMES = 161;
  int NATIONAL = 162;
  int NATURAL = 163;
  int NCHAR = 164;
  int NEXT = 165;
  int NO = 166;
  int NOT = 167;
  int NULL = 168;
  int NULLIF = 169;
  int NUMERIC = 170;
  int OCTET_LENGTH = 171;
  int OF = 172;
  int ON = 173;
  int ONLY = 174;
  int OPEN = 175;
  int OPTION = 176;
  int OR = 177;
  int ORDER = 178;
  int OUTER = 179;
  int OUTPUT = 180;
  int OVERLAPS = 181;
  int PAD = 182;
  int PARTIAL = 183;
  int POSITION = 184;
  int PRECISION = 185;
  int PREPARE = 186;
  int PRESERVE = 187;
  int PRIMARY = 188;
  int PRIOR = 189;
  int PRIVILEGES = 190;
  int PROCEDURE = 191;
  int PUBLIC = 192;
  int READ = 193;
  int REAL = 194;
  int REFERENCES = 195;
  int RELATIVE = 196;
  int RESTRICT = 197;
  int REVOKE = 198;
  int RIGHT = 199;
  int ROLLBACK = 200;
  int ROWS = 201;
  int SCHEMA = 202;
  int SCROLL = 203;
  int SECOND = 204;
  int SECTION = 205;
  int SELECT = 206;
  int SESSION = 207;
  int SESSION_USER = 208;
  int SET = 209;
  int SIZE = 210;
  int SMALLINT = 211;
  int SOME = 212;
  int SPACE = 213;
  int SQL = 214;
  int SQLCODE = 215;
  int SQLERROR = 216;
  int SQLSTATE = 217;
  int SUBSTRING = 218;
  int SUM = 219;
  int SYSTEM_USER = 220;
  int TABLE = 221;
  int TEMPORARY = 222;
  int THEN = 223;
  int TIME = 224;
  int TIMESTAMP = 225;
  int TIMEZONE_HOUR = 226;
  int TIMEZONE_MINUTE = 227;
  int TO = 228;
  int TRAILING = 229;
  int TRANSACTION = 230;
  int TRANSLATE = 231;
  int TRANSLATION = 232;
  int TRIM = 233;
  int TRUE = 234;
  int UNION = 235;
  int UNIQUE = 236;
  int UNKNOWN = 237;
  int UPDATE = 238;
  int UPPER = 239;
  int USAGE = 240;
  int USER = 241;
  int USING = 242;
  int VALUE = 243;
  int VALUES = 244;
  int VARCHAR = 245;
  int VARYING = 246;
  int VIEW = 247;
  int WHEN = 248;
  int WHENEVER = 249;
  int WHERE = 250;
  int WITH = 251;
  int WORK = 252;
  int WRITE = 253;
  int YEAR = 254;
  int ZONE = 255;
  int TOP = 256;
  int XMATCH = 257;
  int REGION = 258;
  int CIRCLE = 259;
  int ELLIPSE = 260;
  int POLYGON = 261;
  int SECTOR = 262;
  int CONVEX = 263;
  int CONVEX_HULL = 264;
  int INTERSECTION = 265;
  int FILL_FACTOR = 266;
  int UNIT = 267;
  int COORD_SYSTEM = 268;
  int CENTER = 269;
  int RADIUS = 270;
  int RADII = 271;
  int POS_ANGLE = 272;
  int DEG = 273;
  int DEG_DEG_M = 274;
  int RAD = 275;
  int H = 276;
  int ARCMIN = 277;
  int ARCSEC = 278;
  int M = 279;
  int KM = 280;
  int MM = 281;
  int AU = 282;
  int PC = 283;
  int KPC = 284;
  int MPC = 285;
  int LYR = 286;
  int ABS = 287;
  int CEILING = 288;
  int DEGREES = 289;
  int EXP = 290;
  int FLOOR = 291;
  int LOG = 292;
  int PI = 293;
  int POWER = 294;
  int RADIANS = 295;
  int SQRT = 296;
  int SQUARE = 297;
  int LOG10 = 298;
  int RAND = 299;
  int ROUND = 300;
  int TRUNCATE = 301;
  int SIN = 302;
  int COS = 303;
  int TAN = 304;
  int COT = 305;
  int ASIN = 306;
  int ACOS = 307;
  int ATAN = 308;
  int ATAN2 = 309;
  int ASCII_STRING_LITERAL = 310;
  int LBRACE = 311;
  int RBRACE = 312;
  int DOLLAR = 313;
  int NOT_EQUALS_OPERATOR = 314;
  int LESS_THAN_OR_EQUALS_OPERATOR = 315;
  int GREATER_THAN_OR_EQUALS_OPERATOR = 316;
  int CROSS_JOIN = 317;
  int GROUPBY = 318;
  int ORDERBY = 319;
  int TIME_ZONE = 320;
  int TRUTH_VALUE = 321;
  int REGULAR_IDENTIFIER = 322;
  int DELIMITED_IDENTIFIER = 323;
  int LETTER = 324;
  int SPECIAL_CHARS = 325;
  int UNSIGNED_INTEGER = 326;
  int DIGIT = 327;
  int APPROXIMATE_NUMERIC_LITERAL = 328;
  int EXACT_NUMERIC_LITERAL = 329;
  int MANTISSA = 330;
  int EXPONENT = 331;
  int SIGNED_INTEGER = 332;
  int E = 333;
  int SIGN = 334;
  int OTHER = 335;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<COMMENT>",
    "<SINGLE_LINE_COMMENT>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\\"\\\"\"",
    "\"%\"",
    "\"&\"",
    "\"\\\'\"",
    "\"(\"",
    "\")\"",
    "\"*\"",
    "\"+\"",
    "\",\"",
    "\"-\"",
    "\".\"",
    "\"/\"",
    "\":\"",
    "\";\"",
    "\"<\"",
    "\"=\"",
    "\">\"",
    "\"?\"",
    "\"_\"",
    "\"|\"",
    "\"[\"",
    "\"]\"",
    "\"absolute\"",
    "\"action\"",
    "\"add\"",
    "\"all\"",
    "\"allocate\"",
    "\"alter\"",
    "\"and\"",
    "\"any\"",
    "\"are\"",
    "\"as\"",
    "\"asc\"",
    "\"assertion\"",
    "\"at\"",
    "\"authorization\"",
    "\"avg\"",
    "\"begin\"",
    "\"between\"",
    "\"bit\"",
    "\"bit_length\"",
    "\"both\"",
    "\"by\"",
    "\"cascade\"",
    "\"cascaded\"",
    "\"case\"",
    "\"cast\"",
    "\"catalog\"",
    "\"char\"",
    "\"character\"",
    "\"char_length\"",
    "\"character_length\"",
    "\"check\"",
    "\"close\"",
    "\"coalesce\"",
    "\"collate\"",
    "\"collation\"",
    "\"column\"",
    "\"commit\"",
    "\"connect\"",
    "\"connection\"",
    "\"constraint\"",
    "\"constraints\"",
    "\"continue\"",
    "\"convert\"",
    "\"corresponding\"",
    "\"count\"",
    "\"create\"",
    "\"cross\"",
    "\"current\"",
    "\"current_date\"",
    "\"current_time\"",
    "\"current_timestamp\"",
    "\"current_user\"",
    "\"cursor\"",
    "\"date\"",
    "\"day\"",
    "\"deallocate\"",
    "\"dec\"",
    "\"decimal\"",
    "\"declare\"",
    "\"default\"",
    "\"deferrable\"",
    "\"deferred\"",
    "\"delete\"",
    "\"desc\"",
    "\"describe\"",
    "\"descriptor\"",
    "\"diagnostics\"",
    "\"disconnect\"",
    "\"distinct\"",
    "\"domain\"",
    "\"double\"",
    "\"drop\"",
    "\"else\"",
    "\"end\"",
    "\"end-exec\"",
    "\"escape\"",
    "\"except\"",
    "\"exception\"",
    "\"exec\"",
    "\"execute\"",
    "\"exists\"",
    "\"external\"",
    "\"extract\"",
    "\"false\"",
    "\"fetch\"",
    "\"first\"",
    "\"float\"",
    "\"for\"",
    "\"foreign\"",
    "\"found\"",
    "\"from\"",
    "\"full\"",
    "\"get\"",
    "\"global\"",
    "\"go\"",
    "\"goto\"",
    "\"grant\"",
    "\"group\"",
    "\"having\"",
    "\"hour\"",
    "\"identity\"",
    "\"immediate\"",
    "\"in\"",
    "\"indicator\"",
    "\"initially\"",
    "\"inner\"",
    "\"input\"",
    "\"insensitive\"",
    "\"insert\"",
    "\"int\"",
    "\"integer\"",
    "\"instersect\"",
    "\"interval\"",
    "\"into\"",
    "\"is\"",
    "\"isolation\"",
    "\"join\"",
    "\"key\"",
    "\"language\"",
    "\"last\"",
    "\"leading\"",
    "\"left\"",
    "\"level\"",
    "\"like\"",
    "\"local\"",
    "\"lower\"",
    "\"match\"",
    "\"max\"",
    "\"min\"",
    "\"minute\"",
    "\"module\"",
    "\"month\"",
    "\"names\"",
    "\"national\"",
    "\"natural\"",
    "\"nchar\"",
    "\"next\"",
    "\"no\"",
    "\"not\"",
    "\"null\"",
    "\"nullif\"",
    "\"numeric\"",
    "\"octet_length\"",
    "\"of\"",
    "\"on\"",
    "\"only\"",
    "\"open\"",
    "\"option\"",
    "\"or\"",
    "\"order\"",
    "\"outer\"",
    "\"output\"",
    "\"overlaps\"",
    "\"pad\"",
    "\"partial\"",
    "\"position\"",
    "\"precision\"",
    "\"prepare\"",
    "\"preserve\"",
    "\"primary\"",
    "\"prior\"",
    "\"privileges\"",
    "\"procedure\"",
    "\"public\"",
    "\"read\"",
    "\"real\"",
    "\"references\"",
    "\"relative\"",
    "\"restrict\"",
    "\"revoke\"",
    "\"right\"",
    "\"rollback\"",
    "\"rows\"",
    "\"schema\"",
    "\"scroll\"",
    "\"second\"",
    "\"section\"",
    "\"select\"",
    "\"session\"",
    "\"session_user\"",
    "\"set\"",
    "\"size\"",
    "\"smallint\"",
    "\"some\"",
    "\"space\"",
    "\"sql\"",
    "\"sqlcode\"",
    "\"sqlerror\"",
    "\"sqlstate\"",
    "\"substring\"",
    "\"sum\"",
    "\"system_user\"",
    "\"table\"",
    "\"temporary\"",
    "\"then\"",
    "\"time\"",
    "\"timestamp\"",
    "\"timezone_hour\"",
    "\"timezone_minute\"",
    "\"to\"",
    "\"trailing\"",
    "\"transaction\"",
    "\"translate\"",
    "\"translation\"",
    "\"trim\"",
    "\"true\"",
    "\"union\"",
    "\"unique\"",
    "\"unknown\"",
    "\"update\"",
    "\"upper\"",
    "\"usage\"",
    "\"user\"",
    "\"using\"",
    "\"value\"",
    "\"values\"",
    "\"varchar\"",
    "\"varying\"",
    "\"view\"",
    "\"when\"",
    "\"whenever\"",
    "\"where\"",
    "\"with\"",
    "\"work\"",
    "\"write\"",
    "\"year\"",
    "\"zone\"",
    "\"top\"",
    "\"xmatch\"",
    "\"region\"",
    "\"circle\"",
    "\"ellipse\"",
    "\"polygon\"",
    "\"sector\"",
    "\"convex\"",
    "\"convex hull\"",
    "\"intersection\"",
    "\"fill factor\"",
    "\"unit\"",
    "<COORD_SYSTEM>",
    "\"center\"",
    "\"radius\"",
    "\"radii\"",
    "\"angle\"",
    "\"deg\"",
    "\"deg deg m\"",
    "\"rad\"",
    "\"h\"",
    "\"arcmin\"",
    "\"arcsec\"",
    "\"m\"",
    "\"km\"",
    "\"mm\"",
    "\"au\"",
    "\"pc\"",
    "\"kpc\"",
    "\"Mpc\"",
    "\"lyr\"",
    "\"abs\"",
    "\"ceiling\"",
    "\"degrees\"",
    "\"exp\"",
    "\"floor\"",
    "\"log\"",
    "\"pi\"",
    "\"power\"",
    "\"radians\"",
    "\"sqrt\"",
    "\"square\"",
    "\"log10\"",
    "\"rand\"",
    "\"round\"",
    "\"truncate\"",
    "\"sin\"",
    "\"cos\"",
    "\"tan\"",
    "\"cot\"",
    "\"asin\"",
    "\"acos\"",
    "\"atan\"",
    "\"atan2\"",
    "<ASCII_STRING_LITERAL>",
    "\"{\"",
    "\"}\"",
    "\"$\"",
    "<NOT_EQUALS_OPERATOR>",
    "\"<=\"",
    "\">=\"",
    "\"cross join\"",
    "\"group by\"",
    "\"order by\"",
    "\"TIME ZONE\"",
    "<TRUTH_VALUE>",
    "<REGULAR_IDENTIFIER>",
    "<DELIMITED_IDENTIFIER>",
    "<LETTER>",
    "<SPECIAL_CHARS>",
    "<UNSIGNED_INTEGER>",
    "<DIGIT>",
    "<APPROXIMATE_NUMERIC_LITERAL>",
    "<EXACT_NUMERIC_LITERAL>",
    "<MANTISSA>",
    "<EXPONENT>",
    "<SIGNED_INTEGER>",
    "<E>",
    "<SIGN>",
    "<OTHER>",
    "\"5-TBD caseExpression\"",
    "\"6-TBD castSpecification\"",
  };

}
