/* Generated By: AdqlStoX.jjt,v 1.18 2006/10/13 21&JJTree: Do not edit this line. ./AdqlStoXTreeConstants.java */

package org.astrogrid.adql;

public interface AdqlStoXTreeConstants
{
  public int JJTVOID = 0;
  public int JJTWHERE = 1;


  public String[] jjtNodeName = {
    "void",
    "Where",
  };
}
