/* Generated By: AdqlStoX.jjt,v 1.33.2.4 2006-12-19 14&JJTree: Do not edit this line. AST_GeneralSetFunction.java */

package org.astrogrid.adql;

import org.astrogrid.adql.v1_0.beans.AggregateFunctionType;
import org.astrogrid.adql.v1_0.beans.AggregateFunctionNameType;
import org.astrogrid.adql.v1_0.beans.ScalarExpressionType;
import org.astrogrid.adql.v1_0.beans.SelectionItemType;

public class AST_GeneralSetFunction extends SimpleNode {
  
    public AST_GeneralSetFunction(AdqlStoX p, int id) {
        super(p, id);
    }

    public void jjtClose() {
        AggregateFunctionType afType = AggregateFunctionType.Factory.newInstance() ;
        ScalarExpressionType seType = (ScalarExpressionType)children[0].getGeneratedObject() ;
        afType.setName( AggregateFunctionNameType.Enum.forString( getFirstToken().image.toUpperCase() ) ) ;
        SelectionItemType[] argArray = new SelectionItemType[1] ;
        argArray[0] = seType ;
        afType.setArgArray( argArray ) ;
        setGeneratedObject( afType ) ;
    }
 
}
