/* Generated By: AdqlStoX.jjt,v 1.33.2.4 2006-12-19 14&JJTree: Do not edit this line. AST_BooleanTerm.java */

package org.astrogrid.adql;

import org.astrogrid.adql.v1_0.beans.SearchType ;
import org.astrogrid.adql.v1_0.beans.IntersectionSearchType ;
import org.apache.commons.logging.Log ;
import org.apache.commons.logging.LogFactory ;


public class AST_BooleanTerm extends SimpleNode {
    
    private static Log log = LogFactory.getLog( AST_BooleanTerm.class ) ;
 
    public AST_BooleanTerm(AdqlStoX p, int id) {
        super(p, id);
    }

    public void jjtClose() {
        if( jjtGetNumChildren() == 1 ) {
            setGeneratedObject( children[0].getGeneratedObject() ) ;
        }
        else {
            SearchType[] conditionArray = new SearchType[2] ;
            IntersectionSearchType andConstruct = IntersectionSearchType.Factory.newInstance() ;
            conditionArray[0] = (SearchType)children[0].getGeneratedObject() ;
            conditionArray[1] = (SearchType)children[1].getGeneratedObject() ;
            andConstruct.setConditionArray( conditionArray ) ;
            setGeneratedObject( andConstruct ) ;
            if( log.isDebugEnabled() ) {
                log.debug( "AND written." ) ;
            }
        }
        
    }
    
}
