/* Generated By: AdqlStoX.jjt,v 1.33.2.4 2006-12-19 14&JJTree: Do not edit this line. AST_ExactNumericLiteral.java */

package org.astrogrid.adql;

import org.astrogrid.adql.v1_0.beans.AtomType ;
import org.astrogrid.adql.v1_0.beans.IntegerType ;
import org.astrogrid.adql.v1_0.beans.RealType ;

public class AST_ExactNumericLiteral extends SimpleNode {
  
    private int possibleSignChange ;

    public AST_ExactNumericLiteral(AdqlStoX p, int id) {
        super(p, id);
    }

    public void setPossibleSignChange( int possibleSignChange ) {
        this.possibleSignChange = possibleSignChange ;
    }

    public void jjtClose() {
        AtomType atomType = AtomType.Factory.newInstance() ; 
        String image = this.parser.token.image ;

        if( image.indexOf( '.' ) == -1 ) {           
            IntegerType intType = IntegerType.Factory.newInstance() ;
            intType.setValue( new Long( image ).longValue() * possibleSignChange ) ;
            atomType.setLiteral( intType ) ;
        }
        else {
            RealType realType = RealType.Factory.newInstance() ;
            realType.setValue( new Double( image ).doubleValue() * possibleSignChange ) ;
            atomType.setLiteral( realType ) ;
        }
        setGeneratedObject( atomType ) ;

    }
  
}
