/* Generated By: AdqlStoX.jjt,v 1.33.2.4 2006-12-19 14&JJTree: Do not edit this line. AST_BooleanPrimary.java */

package org.astrogrid.adql;

import org.astrogrid.adql.v1_0.beans.SearchType ;
import org.astrogrid.adql.v1_0.beans.ClosedSearchType ;

public class AST_BooleanPrimary extends SimpleNode {
    
    private boolean parenthesized = false ;
   
    public AST_BooleanPrimary(AdqlStoX p, int id) {
        super(p, id);
    }
    
    public void setParenthesized() {
        parenthesized = true ;
    }

    public void jjtClose() {   
        if( parenthesized ) {
            ClosedSearchType cs = ClosedSearchType.Factory.newInstance() ;
            cs.setCondition( (SearchType)children[0].getGeneratedObject() ) ;
            setGeneratedObject( cs ) ;   
        }
        else {
            setGeneratedObject( children[0].getGeneratedObject() ) ;
        }
    }
  
}
