/* Generated By: AdqlStoX.jjt,v 1.33.2.4 2006-12-19 14&JJTree: Do not edit this line. AST_InValueList.java */

package org.astrogrid.adql;

import org.astrogrid.adql.v1_0.beans.ConstantListSet;
import org.astrogrid.adql.v1_0.beans.LiteralType;

public class AST_InValueList extends SimpleNode {
 
    public AST_InValueList(AdqlStoX p, int id) {
        super(p, id);
    }

    public void jjtClose() {
        ConstantListSet constantListSet = ConstantListSet.Factory.newInstance() ;
        LiteralType[] literalArray = new LiteralType[ jjtGetNumChildren() ] ;
        for( int i=0; i<literalArray.length; i++ ) {
            literalArray[i] = (LiteralType)children[i].getGeneratedObject() ;
        }
        constantListSet.setItemArray( literalArray ) ;
        setGeneratedObject( constantListSet ) ;
    }  

}
