/* Generated By: AdqlStoX.jjt,v 1.33.2.4 2006-12-19 14&JJTree: Do not edit this line. AST_InValueListConstant.java */

package org.astrogrid.adql;

import org.astrogrid.adql.v1_0.beans.AtomType ;

public class AST_InValueListConstant extends SimpleNode {
 
    public AST_InValueListConstant(AdqlStoX p, int id) {
        super(p, id);
    }

    public void jjtClose() {
        AtomType at = (AtomType)children[0].getGeneratedObject() ;
        setGeneratedObject( at.getLiteral() ) ;
    }

}
