/* Generated By: AdqlStoX.jjt,v 1.33.2.4 2006-12-19 14&JJTree: Do not edit this line. AST_TrigFunction.java */

package org.astrogrid.adql;

import org.astrogrid.adql.v1_0.beans.TrigonometricFunctionType;
import org.astrogrid.adql.v1_0.beans.ScalarExpressionType;
import org.astrogrid.adql.v1_0.beans.TrigonometricFunctionNameType;
import org.astrogrid.adql.v1_0.beans.SelectionItemType;

public class AST_TrigFunction extends SimpleNode {
  
    public AST_TrigFunction(AdqlStoX p, int id) {
        super(p, id);
    }

    public void jjtClose() {
        TrigonometricFunctionType tfType = TrigonometricFunctionType.Factory.newInstance() ;
        tfType.setName( TrigonometricFunctionNameType.Enum.forString( firstToken.image.toUpperCase() ) ) ;
        SelectionItemType[] argArray ;

        if( firstToken.kind == AdqlStoXConstants.ATAN2 ) {
            argArray = new SelectionItemType[2] ;
            argArray[0] = (ScalarExpressionType)children[0].getGeneratedObject() ;
            argArray[1] = (ScalarExpressionType)children[1].getGeneratedObject() ;
        }
        else {
            argArray = new SelectionItemType[1] ;
            argArray[0] = (ScalarExpressionType)children[0].getGeneratedObject() ;
        }
        tfType.setArgArray( argArray ) ;
        setGeneratedObject( tfType ) ;
    }

}
