/* Generated By: AdqlStoX.jjt,v 1.33.2.4 2006-12-19 14&JJTree: Do not edit this line. AST_OrderingSpecification.java */

package org.astrogrid.adql;

import org.astrogrid.adql.v1_0.beans.OrderOptionType;
import org.astrogrid.adql.v1_0.beans.OrderDirectionType;

public class AST_OrderingSpecification extends SimpleNode {

    public AST_OrderingSpecification(AdqlStoX p, int id) {
        super(p, id);
    }

    public void jjtClose() {
        OrderOptionType optionType = OrderOptionType.Factory.newInstance() ;
        OrderDirectionType.Enum 
           direction = OrderDirectionType.Enum.forString( parser.token.image.toUpperCase() ) ;
        optionType.setDirection( direction ) ;  
        setGeneratedObject( optionType ) ;
    }
  
}
