/* Generated By:JJTree: Do not edit this line. ASTOrderBy.java */

package org.astrogrid.adql;

import org.apache.xmlbeans.*;
import org.astrogrid.adql.v1_0.beans.*;

public class ASTOrderBy extends SimpleNode {
  public ASTOrderBy(int id) {
    super(id);
  }

  public ASTOrderBy(AdqlStoX p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AdqlStoXVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
