/* Generated By:JJTree: Do not edit this line. ASTRestrict.java */

package org.astrogrid.adql;

import org.apache.xmlbeans.*;
import org.astrogrid.adql.v1_0.beans.*;

public class ASTRestrict extends SimpleNode {
	
	int value ;
	
  public ASTRestrict(int id) {
    super(id);
  }

  public ASTRestrict(AdqlStoX p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AdqlStoXVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

/**
 * @return the value
 */
public int getValue() {
	return value;
}

/**
 * @param value the value to set
 */
public void setValue(int value) {
	this.value = value;
}
}
