/* Generated By:JJTree: Do not edit this line. ASTSelectionList.java */

package org.astrogrid.adql;

import java.util.ArrayList;
import org.apache.xmlbeans.*;
import org.astrogrid.adql.v1_0.beans.*;

public class ASTSelectionList extends SimpleNode {
	
	ArrayList itemList = new ArrayList() ;
	
	public ASTSelectionList(int id) {
		super(id);
	}

	public ASTSelectionList(AdqlStoX p, int id) {
		super(p, id);
	}


	/** Accept the visitor. **/
	public Object jjtAccept(AdqlStoXVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}
}
