/*
 * $Id: CoordFlavorType.java,v 1.2 2011/09/13 13:43:24 pah Exp $
 * Copyright 2011 Paul Harrison (paul.harrison@manchester.ac.uk)
 *
 * File originally generated by JAXB, but since hand updated
 */


package net.ivoa.xml.stc.stc_v1_30_prov;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * Provides the spatial coordinate definitions: number of axes, SPHERICAL, CARTESIAN, UNITSPHERE, POLAR, or HEALPIX, presence of velocities.
 * 
 * <p>Java class for coordFlavorType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="coordFlavorType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="coord_naxes" default="2">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *             &lt;minInclusive value="1"/>
 *             &lt;maxInclusive value="3"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="handedness">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="left"/>
 *             &lt;enumeration value="right"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "coordFlavorType")
public class CoordFlavorType {

    @XmlAttribute(name = "coord_naxes")
    protected Integer coordNaxes;
    @XmlAttribute
    protected String handedness;

    /**
     * Gets the value of the coordNaxes property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getCoordNaxes() {
        if (coordNaxes == null) {
            return  2;
        } else {
            return coordNaxes;
        }
    }

    /**
     * Sets the value of the coordNaxes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCoordNaxes(Integer value) {
        this.coordNaxes = value;
    }

    /**
     * Gets the value of the handedness property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHandedness() {
        return handedness;
    }

    /**
     * Sets the value of the handedness property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHandedness(String value) {
        this.handedness = value;
    }

}
