/*
 * $Id: FitsType.java,v 1.2 2011/09/13 13:43:22 pah Exp $
 * Copyright 2011 Paul Harrison (paul.harrison@manchester.ac.uk)
 *
 * File originally generated by JAXB, but since hand updated
 */


package net.ivoa.xml.stc.stc_v1_30_prov;

import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * Specifies a FITS file and optionally a specific HDU by HDU number or HDU name.
 * 
 * <p>Java class for fitsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="fitsType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>anyURI">
 *       &lt;attribute name="hdu_name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="hdu_num" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "fitsType", propOrder = {
    "value"
})
public class FitsType {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "hdu_name")
    protected String hduName;
    @XmlAttribute(name = "hdu_num")
    protected BigInteger hduNum;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the hduName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHduName() {
        return hduName;
    }

    /**
     * Sets the value of the hduName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHduName(String value) {
        this.hduName = value;
    }

    /**
     * Gets the value of the hduNum property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getHduNum() {
        return hduNum;
    }

    /**
     * Sets the value of the hduNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setHduNum(BigInteger value) {
        this.hduNum = value;
    }

}
