/*
 * $Id: SpectralIntervalType.java,v 1.2 2011/09/13 13:43:23 pah Exp $
 * Copyright 2011 Paul Harrison (paul.harrison@manchester.ac.uk)
 *
 * File originally generated by JAXB, but since hand updated
 */


package net.ivoa.xml.stc.stc_v1_30_prov;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * Contains a 1-D spectral interval.
 * 
 * <p>Java class for spectralIntervalType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="spectralIntervalType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ivoa.net/xml/STC/stc-v1.30.xsd}coordScalarIntervalType">
 *       &lt;attribute name="unit" use="required" type="{http://www.ivoa.net/xml/STC/stc-v1.30.xsd}spectralUnitType" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "spectralIntervalType")
public class SpectralIntervalType
    extends CoordScalarIntervalType
{

    @XmlAttribute(required = true)
    protected SpectralUnitType unit;

    /**
     * Gets the value of the unit property.
     * 
     * @return
     *     possible object is
     *     {@link SpectralUnitType }
     *     
     */
    public SpectralUnitType getUnit() {
        return unit;
    }

    /**
     * Sets the value of the unit property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpectralUnitType }
     *     
     */
    public void setUnit(SpectralUnitType value) {
        this.unit = value;
    }

}
