/*
 * $Id: StdRefPosType.java,v 1.2 2011/09/13 13:43:24 pah Exp $
 * Copyright 2011 Paul Harrison (paul.harrison@manchester.ac.uk)
 *
 * File originally generated by JAXB, but since hand updated
 */


package net.ivoa.xml.stc.stc_v1_30_prov;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * Type for standard reference positions.
 * 
 * <p>Java class for stdRefPosType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="stdRefPosType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ivoa.net/xml/STC/stc-v1.30.xsd}referencePositionType">
 *       &lt;sequence>
 *         &lt;element name="PlanetaryEphem" type="{http://www.ivoa.net/xml/STC/stc-v1.30.xsd}planetaryEphemType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "stdRefPosType", propOrder = {
    "planetaryEphem"
})
public class StdRefPosType
    extends ReferencePositionType
{

    @XmlElementRef(name = "PlanetaryEphem", namespace = "http://www.ivoa.net/xml/STC/stc-v1.30.xsd", type = JAXBElement.class)
    protected JAXBElement<PlanetaryEphemType> planetaryEphem;

    /**
     * Gets the value of the planetaryEphem property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link PlanetaryEphemType }{@code >}
     *     
     */
    public JAXBElement<PlanetaryEphemType> getPlanetaryEphem() {
        return planetaryEphem;
    }

    /**
     * Sets the value of the planetaryEphem property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link PlanetaryEphemType }{@code >}
     *     
     */
    public void setPlanetaryEphem(JAXBElement<PlanetaryEphemType> value) {
        this.planetaryEphem = ((JAXBElement<PlanetaryEphemType> ) value);
    }

}
